(() => {
  const Core = window.AlgoriZoomCore;
  const PROBLEM = Object.freeze({
    number:"5205", title:"퀵 정렬", autoplayMs:520, defaultSampleId:"all",
    samples:[
      {id:"one",label:"샘플 1",value:"1\n5\n2 2 1 1 3"},
      {id:"two",label:"샘플 2",value:"1\n10\n7 5 4 1 2 10 3 6 9 8"},
      {id:"all",label:"전체 샘플",value:"2\n5\n2 2 1 1 3\n10\n7 5 4 1 2 10 3 6 9 8"},
    ],
    sourceSteps:[
      {text:"def quick(start, end):",types:"call"},
      {text:"if start >= end:",types:"baseCheck"},
      {text:"return",types:"baseReturn"},
      {text:"pivot = start",types:"pivotInit"},
      {text:"left = start + 1",types:"leftInit"},
      {text:"right = end",types:"rightInit"},
      {text:"while True:",types:"outerLoop"},
      {text:"while left <= end and A[left] <= A[pivot]:",types:"scanLeft"},
      {text:"left += 1",types:"leftInc"},
      {text:"while right > start and A[right] > A[pivot]:",types:"scanRight"},
      {text:"right -= 1",types:"rightDec"},
      {text:"if left > right:",types:"crossCheck"},
      {text:"break",types:"crossBreak"},
      {text:"A[left], A[right] = A[right], A[left]",types:"swapLR"},
      {text:"A[right], A[pivot] = A[pivot], A[right]",types:"pivotSwap"},
      {text:"quick(start, right - 1)",types:"leftCall"},
      {text:"quick(right + 1, end)",types:"rightCall"},
      {text:"A = list(map(int, input().split()))",types:"caseInput"},
      {text:"quick(0, N - 1)",types:"startSort"},
      {text:"print('#{} {}'.format(tc, A[N//2]))",types:"output"},
    ],
  });
  const els=Core.getByIds(["sourceCode","codeView","mobileCodeView","codeViewport","mobileCodeViewport","resetBtn","prevBtn","nextBtn","playBtn","replayBtn","skipBtn","speedRange","speedLabel","timeline","mobileTimeline","stepLabel","mobileTimelineStatus","mobilePlayBtn","mobilePrevBtn","mobileNextBtn","codeLineLabel","mobileCodeStatus","board","mobileBoard","boardLabel","phaseLabel","mobilePhase","startValue","endValue","pivotValue","leftValue","rightValue","pivotItemValue","explainText","mobileCoord","mobileExplanation","mobileStateMeta","mobileStart","mobileEnd","mobileLeft","mobileRight","detailView","mobileDetailView","detailMeta","outputView","mobileOutputView","inputArea","applyBtn","sampleButtons","inputError"]);
  const state={steps:[],stepIndex:0,timer:null,speed:1,selectedSample:PROBLEM.defaultSampleId}; let desktopLines,mobileLines,stepLines;

  function parseInput(text){const t=text.trim().split(/\s+/).filter(Boolean).map(Number);if(!t.length||t.some(v=>!Number.isFinite(v)))throw new Error("숫자로 된 입력을 확인해주세요.");let p=0,T=t[p++],cases=[];if(!Number.isInteger(T)||T<1||T>10)throw new Error("시각화에서는 T를 1~10으로 입력해주세요.");for(let tc=0;tc<T;tc++){let N=t[p++];if(!Number.isInteger(N)||N<5||N>60)throw new Error(`#${tc+1}의 N은 시각화를 위해 5~60으로 입력해주세요.`);if(p+N>t.length)throw new Error(`#${tc+1}의 배열 원소가 부족합니다.`);let A=t.slice(p,p+N);p+=N;if(A.some(v=>!Number.isInteger(v)||v<0||v>1000000))throw new Error("배열 원소는 0~1,000,000의 정수여야 합니다.");cases.push({N,A});}if(p!==t.length)throw new Error("입력 끝에 사용되지 않은 값이 있습니다.");return cases;}

  function buildSteps(cases){const steps=[];let output="";cases.forEach((item,ci)=>{let A=[...item.A];const history=[];const push=(phase,message,extra={})=>steps.push({tc:ci+1,N:item.N,A:[...A],start:null,end:null,pivot:null,left:null,right:null,depth:0,swapIndices:[],pivotPlaced:null,pivotValue:null,phase,message,history:history.map(v=>({...v})),output,...extra,swapIndices:[...(extra.swapIndices||[])]});push("caseInput",`#${ci+1} 입력 배열을 확인합니다: ${A.join(", ")}`);push("startSort",`quick(0, ${item.N-1})을 호출해 전체 배열 정렬을 시작합니다.`,{start:0,end:item.N-1});
    function quick(start,end,depth){const snap=(phase,message,extra={})=>push(phase,message,{start,end,depth,...extra});snap("call",`quick(${start}, ${end}) 호출 · 현재 정렬 구간을 확인합니다.`);snap("baseCheck",`start >= end → ${start} >= ${end} = ${start>=end?"참":"거짓"}`);if(start>=end){snap("baseReturn","원소가 0개 또는 1개인 구간이므로 바로 반환합니다.");return;}let pivot=start;const pValue=A[pivot];snap("pivotInit",`pivot = start = ${pivot}, pivot 값은 ${pValue}입니다.`,{pivot,pivotValue:pValue});let left=start+1;snap("leftInit",`left를 ${left}에서 시작합니다.`,{pivot,left,pivotValue:pValue});let right=end;snap("rightInit",`right를 ${right}에서 시작합니다.`,{pivot,left,right,pivotValue:pValue});while(true){snap("outerLoop",`left=${left}, right=${right}에서 양쪽 포인터 탐색을 시작합니다.`,{pivot,left,right,pivotValue:pValue});while(left<=end && A[left]<=A[pivot]){snap("scanLeft",`A[${left}] = ${A[left]} ≤ pivot ${A[pivot]} 이므로 left가 지나갈 수 있습니다.`,{pivot,left,right,pivotValue:pValue});left+=1;snap("leftInc",`left를 ${left}로 한 칸 이동합니다.`,{pivot,left,right,pivotValue:pValue});}snap("scanLeft",left>end?`left=${left}가 end=${end}를 넘어 왼쪽 탐색을 멈춥니다.`:`A[${left}] = ${A[left]} > pivot ${A[pivot]}이므로 left가 멈춥니다.`,{pivot,left,right,pivotValue:pValue});while(right>start && A[right]>A[pivot]){snap("scanRight",`A[${right}] = ${A[right]} > pivot ${A[pivot]}이므로 right가 지나갑니다.`,{pivot,left,right,pivotValue:pValue});right-=1;snap("rightDec",`right를 ${right}로 한 칸 이동합니다.`,{pivot,left,right,pivotValue:pValue});}snap("scanRight",right<=start?`right=${right}가 start=${start}에 도달해 오른쪽 탐색을 멈춥니다.`:`A[${right}] = ${A[right]} ≤ pivot ${A[pivot]}이므로 right가 멈춥니다.`,{pivot,left,right,pivotValue:pValue});const crossed=left>right;snap("crossCheck",`left > right → ${left} > ${right} = ${crossed?"참":"거짓"}`,{pivot,left,right,pivotValue:pValue});if(crossed){snap("crossBreak","두 포인터가 교차했으므로 반복을 끝내고 pivot을 제자리로 옮깁니다.",{pivot,left,right,pivotValue:pValue});break;}const beforeL=A[left],beforeR=A[right];[A[left],A[right]]=[A[right],A[left]];history.push({type:"swap",text:`${left}↔${right}: ${beforeL}↔${beforeR}`});snap("swapLR",`A[${left}]과 A[${right}]을 교환합니다: ${beforeL} ↔ ${beforeR}`,{pivot,left,right,pivotValue:pValue,swapIndices:[left,right]});}
      const beforePivot=A[pivot],beforeRight=A[right];[A[right],A[pivot]]=[A[pivot],A[right]];history.push({type:"pivot",text:`pivot ${pivot}→${right}: ${beforePivot}`});snap("pivotSwap",`pivot 값 ${beforePivot}을 ${right}번 위치로 옮깁니다.`,{pivot,left,right,pivotValue:pValue,pivotPlaced:right,swapIndices:[pivot,right]});snap("leftCall",`pivot 왼쪽 [${start}, ${right-1}]을 재귀 정렬합니다.`,{pivot,left,right,pivotValue:pValue,pivotPlaced:right});quick(start,right-1,depth+1);snap("rightCall",`pivot 오른쪽 [${right+1}, ${end}]을 재귀 정렬합니다.`,{pivot,left,right,pivotValue:pValue,pivotPlaced:right});quick(right+1,end,depth+1);}
    quick(0,item.N-1,0);output+=`#${ci+1} ${A[item.N>>1]}\n`;push("output",`정렬 완료: A[N//2] = A[${item.N>>1}] = ${A[item.N>>1]}를 출력합니다.`,{start:0,end:item.N-1});});return steps;}

  const names={caseInput:"입력 배열",startSort:"정렬 시작",call:"quick 호출",baseCheck:"기저 조건",baseReturn:"재귀 반환",pivotInit:"pivot 선택",leftInit:"left 초기화",rightInit:"right 초기화",outerLoop:"포인터 탐색",scanLeft:"left 탐색",leftInc:"left 이동",scanRight:"right 탐색",rightDec:"right 이동",crossCheck:"포인터 교차 확인",crossBreak:"반복 종료",swapLR:"left/right 교환",pivotSwap:"pivot 배치",leftCall:"왼쪽 재귀",rightCall:"오른쪽 재귀",output:"출력"};
  function board(container,s){const cells=s.A.map((v,i)=>{const cls=["array-cell"];if(s.start!==null&&(i<s.start||i>s.end))cls.push("outside");else if(s.start!==null)cls.push("range");if(i===s.pivot && s.phase!=="pivotSwap")cls.push("pivot");if(i===s.pivotPlaced)cls.push("pivot");if(i===s.left)cls.push("left");if(i===s.right)cls.push("right");if(s.swapIndices.includes(i))cls.push("swap");return `<span class="${cls.join(" ")}">${v}<small>${i}</small></span>`}).join("");container.innerHTML=`<div class="quick-wrap"><p class="quick-title"><span>A</span><span>${s.start===null?"전체 배열":`[${s.start}, ${s.end}] · depth ${s.depth}`}</span></p><div class="array-row">${cells}</div><div class="pointer-legend"><span class="legend-chip pivot">pivot</span><span class="legend-chip left">left</span><span class="legend-chip right">right</span><span class="legend-chip swap">교환</span></div></div>`;}
  function detail(container,s){const recent=s.history.slice(-5);let html=`<span class="detail-chip call">현재 구간 <strong>${s.start===null?"—":`[${s.start}, ${s.end}]`}</strong></span><span class="detail-chip">재귀 깊이 <strong>${s.depth}</strong></span>`;if(s.pivotValue!==null)html+=`<span class="detail-chip">pivot 값 <strong>${s.pivotValue}</strong></span>`;for(const h of recent)html+=`<span class="detail-chip ${h.type==="swap"?"swap":""}">${h.text}</span>`;container.innerHTML=html;}
  function highlight(lines,n){lines.forEach((line,k)=>line.classList.toggle("active",k===n));}
  function renderD(s){const ln=stepLines.get(s.phase);highlight(desktopLines,ln);board(els.board,s);detail(els.detailView,s);els.codeLineLabel.textContent=ln?`LINE ${ln}`:names[s.phase];els.boardLabel.textContent=`#${s.tc} · N=${s.N}`;els.phaseLabel.textContent=names[s.phase];els.startValue.textContent=s.start??"—";els.endValue.textContent=s.end??"—";els.pivotValue.textContent=s.pivot??"—";els.leftValue.textContent=s.left??"—";els.rightValue.textContent=s.right??"—";els.pivotItemValue.textContent=s.pivotValue??"—";els.explainText.textContent=s.message;els.detailMeta.textContent=s.start===null?"시작 전":`depth ${s.depth}`;els.outputView.textContent=s.output||"아직 출력이 없습니다.";}
  function renderM(s){const ln=stepLines.get(s.phase);highlight(mobileLines,ln);board(els.mobileBoard,s);detail(els.mobileDetailView,s);els.mobileCoord.textContent=`#${s.tc} · pivot = ${s.pivot??"—"}`;els.mobileCodeStatus.textContent=ln?`LINE ${ln}`:names[s.phase];els.mobilePhase.textContent=names[s.phase];els.mobileExplanation.textContent=s.message;els.mobileStateMeta.textContent=s.pivotValue===null?"pivot / left / right":`pivot 값 ${s.pivotValue}`;els.mobileStart.textContent=s.start??"—";els.mobileEnd.textContent=s.end??"—";els.mobileLeft.textContent=s.left??"—";els.mobileRight.textContent=s.right??"—";els.mobileOutputView.textContent=s.output||"아직 출력이 없습니다.";}
  function sync(){let e=!state.steps.length;els.prevBtn.disabled=els.mobilePrevBtn.disabled=e||state.stepIndex===0;els.nextBtn.disabled=els.mobileNextBtn.disabled=e||state.stepIndex===state.steps.length-1;[els.playBtn,els.replayBtn,els.resetBtn,els.skipBtn,els.timeline,els.mobileTimeline,els.mobilePlayBtn].forEach(x=>x.disabled=e)}
  function render({follow=true}={}){let s=state.steps[state.stepIndex];if(!s)return;renderD(s);renderM(s);els.timeline.value=els.mobileTimeline.value=state.stepIndex;els.stepLabel.textContent=els.mobileTimelineStatus.textContent=`${state.stepIndex+1} / ${state.steps.length}`;sync();if(follow){let ln=stepLines.get(s.phase);if(ln){Core.centerInsideViewport(els.codeViewport,desktopLines.get(ln),{horizontal:false});Core.centerInsideViewport(els.mobileCodeViewport,mobileLines.get(ln),{horizontal:false});}}}
  function stop(){if(state.timer!==null)clearTimeout(state.timer);state.timer=null;Core.updatePlaybackControls(els.playBtn,false)}function go(i,o={}){if(!state.steps.length)return;state.stepIndex=Core.clamp(i,0,state.steps.length-1);render(o)}function move(d){stop();go(state.stepIndex+d)}function sched(){state.timer=setTimeout(()=>{if(state.stepIndex>=state.steps.length-1){stop();return}go(state.stepIndex+1);if(state.stepIndex>=state.steps.length-1)stop();else sched()},PROBLEM.autoplayMs/state.speed)}function start(){if(!state.steps.length)return;stop();if(state.stepIndex>=state.steps.length-1)go(0);Core.updatePlaybackControls(els.playBtn,true);sched()}function reset(){stop();go(0)}
  function sampleButtons(){els.sampleButtons.replaceChildren();PROBLEM.samples.forEach(s=>{let b=document.createElement("button");b.type="button";b.className="btn";b.textContent=s.label;b.dataset.sample=s.id;b.classList.toggle("selected",state.selectedSample===s.id);els.sampleButtons.append(b)})}function apply(text,id=null){stop();try{state.steps=buildSteps(parseInput(text));state.stepIndex=0;state.selectedSample=id;els.inputError.textContent="";els.timeline.max=els.mobileTimeline.max=Math.max(0,state.steps.length-1);sampleButtons();render()}catch(e){state.selectedSample=null;els.inputError.textContent=e.message;sampleButtons()}}
  const markup=Core.createCodeMarkup(els.sourceCode,PROBLEM.sourceSteps,{wrap:false,editor:true});els.codeView.innerHTML=els.mobileCodeView.innerHTML=markup;desktopLines=Core.createLineMap(els.codeView);mobileLines=Core.createLineMap(els.mobileCodeView);stepLines=Core.createStepLineMap(els.codeView);
  els.prevBtn.onclick=()=>move(-1);els.nextBtn.onclick=()=>move(1);els.mobilePrevBtn.onclick=()=>move(-1);els.mobileNextBtn.onclick=()=>move(1);els.mobilePlayBtn.onclick=()=>els.playBtn.click();els.playBtn.onclick=()=>state.timer===null?start():stop();els.resetBtn.onclick=reset;els.replayBtn.onclick=()=>{reset();start()};els.skipBtn.onclick=()=>{stop();go(state.steps.length-1)};els.speedRange.oninput=()=>{state.speed=Number(els.speedRange.value);els.speedLabel.textContent=`${Core.formatDecimal(state.speed)}×`;if(state.timer!==null){clearTimeout(state.timer);sched()}};[els.timeline,els.mobileTimeline].forEach(x=>x.oninput=e=>{stop();go(Number(e.target.value))});els.applyBtn.onclick=()=>apply(els.inputArea.value);els.inputArea.oninput=()=>{state.selectedSample=null;sampleButtons()};els.sampleButtons.onclick=e=>{let b=e.target.closest("button[data-sample]");if(!b)return;let s=PROBLEM.samples.find(v=>v.id===b.dataset.sample);if(!s)return;els.inputArea.value=s.value;apply(s.value,s.id)};let d=PROBLEM.samples.find(s=>s.id===PROBLEM.defaultSampleId);sampleButtons();els.inputArea.value=d.value;apply(d.value,d.id);
})();
