(() => {
  const Core = window.AlgoriZoomCore;
  const PROBLEM = Object.freeze({ platform:"SWEA", number:"5099", level:"D3", title:"피자 굽기", autoplayMs:650, defaultSampleId:"one",
    sourceSteps:[
      {text:"pan = [[0, 0] for _ in range(N)]",types:"makePan",occurrence:1},{text:"for i in range(N):",types:"fill",occurrence:1},{text:"pan[i][0] = i+1",types:"fill",occurrence:1},{text:"pan[i][1] = pizza[i]",types:"fill",occurrence:1},{text:"next_pizza = N+1",types:"nextReady",occurrence:1},{text:"while len(pan) > 1:",types:"while",occurrence:1},{text:"current = pan.pop(0)",types:"pop",occurrence:1},{text:"current[1] = current[1]//2",types:"halve",occurrence:1},{text:"if current[1] == 0:",types:"meltCheck",occurrence:1},{text:"if next_pizza <= M:",types:"hasWaiting",occurrence:1},{text:"pan.append([next_pizza, pizza[next_pizza - 1]])",types:"replace",occurrence:1},{text:"next_pizza += 1",types:"advance",occurrence:1},{text:"pan.append(current)",types:"rotate",occurrence:1},{text:"print('#{} {}'.format(tc, pan[0][0]))",types:"output",occurrence:1}
    ],
    samples:[{id:"one",label:"샘플 1 · 큐 흐름",value:"1\n3 5\n7 2 6 5 3"},{id:"all",label:"첨부 예제 전체",value:"3\n3 5\n7 2 6 5 3\n5 10\n5 9 3 9 9 2 5 8 7 1\n5 10\n20 4 5 7 3 15 2 1 2 2"}]
  });
  const samples=PROBLEM.samples, defaultSample=samples[0];
  const els=Core.getByIds(["sourceCode","resetBtn","prevBtn","nextBtn","playBtn","replayBtn","skipBtn","speedRange","speedLabel","stepLabel","timeline","codeLineLabel","codeViewport","codeView","boardLabel","boardViewport","board","phaseLabel","currentValue","cheeseValue","nextPizzaValue","panLengthValue","operationValue","winnerValue","explainText","waitingQueue","waitingLabel","outputView","inputArea","applyBtn","sampleButtons","inputError","mobileCoord","mobileCodeStatus","mobileCodeViewport","mobileCodeView","mobilePhase","mobileBoardViewport","mobileBoard","mobileWaitingQueue","mobileExplanation","mobileStateMeta","mobileCurrent","mobileCheese","mobileNextPizza","mobilePanLength","mobileWinner","mobileOutputView","mobilePrevBtn","mobileTimeline","mobileTimelineStatus","mobileNextBtn"]);
  const state={cases:[],steps:[],stepIndex:0,timer:null,speed:1,selectedSample:defaultSample.id,codeLines:null,mobileCodeLines:null}; let stepLineMap;
  function renderCode(){const markup=Core.createCodeMarkup(els.sourceCode,PROBLEM.sourceSteps,{wrap:false,editor:true});els.codeView.innerHTML=markup;els.mobileCodeView.innerHTML=markup;state.codeLines=Core.createLineMap(els.codeView);state.mobileCodeLines=Core.createLineMap(els.mobileCodeView);stepLineMap=Core.createStepLineMap(els.codeView);}
  function parseInput(text){const tokens=text.trim().split(/\s+/);if(!text.trim()||tokens.some(t=>!/^\d+$/.test(t)))throw new Error("입력은 양의 정수로 작성해주세요.");const values=tokens.map(Number),T=values[0];if(T<1||T>50)throw new Error("T는 1 이상 50 이하입니다.");let cursor=1;const cases=[];for(let tc=0;tc<T;tc++){if(cursor+2>values.length)throw new Error("각 케이스의 N과 M을 확인해주세요.");const N=values[cursor++],M=values[cursor++];if(N<3||N>20||M<N||M>100)throw new Error("N은 3~20, M은 N~100 범위여야 합니다.");const pizzas=values.slice(cursor,cursor+M);cursor+=M;if(pizzas.length!==M||pizzas.some(v=>v<1||v>20))throw new Error("각 케이스에 1~20 범위의 치즈 양 M개를 입력해주세요.");cases.push({N,M,pizzas});}if(cursor!==values.length)throw new Error("T와 케이스 수, M과 치즈 양 개수를 확인해주세요.");return{cases};}
  function buildSteps(){const steps=[];let output="";state.cases.forEach((data,index)=>{const {N,M,pizzas}=data;let pan=[],nextPizza=N+1,current=null,before=null,after=null,winner=null,operation="초기화";const push=(phase,message,extra={})=>steps.push({...data,tc:index+1,pan:pan.map(p=>[...p]),nextPizza,current:current&&[...current],before,after,winner,operation,phase,line:stepLineMap.get(phase),message,output,...extra});push("makePan",`피자 ${N}개가 들어갈 화덕 큐를 만듭니다.`);for(let i=0;i<N;i++){pan.push([i+1,pizzas[i]]);operation=`append(${i+1}번)`;push("fill",`${i+1}번 피자(치즈 ${pizzas[i]})를 화덕 뒤에 넣습니다.`,{inserted:i+1});}operation="대기 번호 설정";push("nextReady",`다음으로 넣을 피자는 ${nextPizza}번입니다.`);while(pan.length>1){operation="len(pan) > 1";push("while",`화덕에 ${pan.length}개가 남아 있으므로 계속 굽습니다.`);current=pan.shift();before=current[1];after=before;operation="pop(0)";push("pop",`큐의 맨 앞 ${current[0]}번 피자를 꺼냅니다.`,{popped:current[0]});after=Math.floor(before/2);current[1]=after;operation=`${before} // 2`;push("halve",`한 바퀴 돌아 ${current[0]}번 피자의 치즈가 ${before} → ${after}로 줄었습니다.`);operation=after===0?"치즈가 모두 녹음":"치즈가 남음";push("meltCheck",`current[1] == 0은 ${after===0?"참":"거짓"}입니다.`);if(after===0){operation=nextPizza<=M?"대기 피자 있음":"대기 피자 없음";push("hasWaiting",nextPizza<=M?`${nextPizza}번 피자를 바로 빈자리에 넣을 수 있습니다.`:"더 넣을 피자가 없어 빈자리를 그대로 둡니다.");if(nextPizza<=M){const inserted=nextPizza;pan.push([inserted,pizzas[inserted-1]]);operation=`append(${inserted}번)`;push("replace",`${inserted}번 피자(치즈 ${pizzas[inserted-1]})를 화덕 뒤에 넣습니다.`,{inserted});nextPizza++;operation="next_pizza += 1";push("advance",`다음 대기 번호를 ${nextPizza}로 옮깁니다.`);}}else{pan.push([...current]);operation=`append(${current[0]}번)`;push("rotate",`치즈가 남은 ${current[0]}번 피자를 큐의 맨 뒤에 다시 넣습니다.`,{inserted:current[0]});}}
      winner=pan[0][0];current=null;before=after=null;operation="종료";output+=`#${index+1} ${winner}\n`;push("output",`화덕에 마지막으로 남은 피자는 ${winner}번입니다.`);
    });state.steps=steps;}
  function pizzaCard(pizza,index,step){const card=document.createElement("div");card.className="pizza-card";if(index===0)card.classList.add("front");if(step.inserted===pizza[0])card.classList.add("inserted");card.innerHTML=`<strong>${pizza[0]}번 피자</strong><small>치즈 ${pizza[1]}</small>`;return card;}
  function renderQueue(container,step){container.replaceChildren();if(step.phase==="pop"||step.phase==="halve"||step.phase==="meltCheck"||step.phase==="hasWaiting"){if(step.current){const card=pizzaCard(step.current,-1,step);card.classList.add("current");if(step.after===0)card.classList.add("melted");container.appendChild(card);}}step.pan.forEach((pizza,index)=>container.appendChild(pizzaCard(pizza,index,step)));if(!container.children.length){const empty=document.createElement("p");empty.className="queue-empty";empty.textContent="화덕 큐가 비어 있습니다.";container.appendChild(empty);}}
  function renderWaiting(container,step){container.replaceChildren();step.pizzas.forEach((cheese,i)=>{const number=i+1,item=document.createElement("div");item.className="waiting-item";if(number<step.nextPizza)item.classList.add("used");if(number===step.nextPizza)item.classList.add("next");item.innerHTML=`${number}번<br>치즈 ${cheese}`;container.appendChild(item);});}
  function highlight(lines,n){lines.forEach((line,number)=>line.classList.toggle("active",number===n));}
  function render({follow=true}={}){const step=state.steps[state.stepIndex];if(!step)return;highlight(state.codeLines,step.line);highlight(state.mobileCodeLines,step.line);renderQueue(els.board,step);renderQueue(els.mobileBoard,step);renderWaiting(els.waitingQueue,step);renderWaiting(els.mobileWaitingQueue,step);const current=step.current?`${step.current[0]}번` : "—",cheese=step.before==null?"—":`${step.before} → ${step.after}`,next=step.nextPizza<=step.M?`${step.nextPizza}번`:"없음",winner=step.winner?`${step.winner}번`:"—";els.codeLineLabel.textContent=`LINE ${step.line}`;els.boardLabel.textContent=`#${step.tc} · N=${step.N} · M=${step.M}`;els.phaseLabel.textContent=step.phase.toUpperCase();els.currentValue.textContent=current;els.cheeseValue.textContent=cheese;els.nextPizzaValue.textContent=next;els.panLengthValue.textContent=step.pan.length;els.operationValue.textContent=step.operation;els.winnerValue.textContent=winner;els.explainText.textContent=step.message;els.waitingLabel.textContent=next==="없음"?"투입 완료":`${next} 투입 대기`;els.outputView.textContent=step.output||"아직 출력이 없습니다.";els.mobileCoord.textContent=`#${step.tc} · N=${step.N}`;els.mobileCodeStatus.textContent=`LINE ${step.line}`;els.mobilePhase.textContent=step.phase.toUpperCase();els.mobileExplanation.textContent=step.message;els.mobileStateMeta.textContent=`M=${step.M} · ${step.operation}`;els.mobileCurrent.textContent=current;els.mobileCheese.textContent=step.after??"—";els.mobileNextPizza.textContent=next;els.mobilePanLength.textContent=step.pan.length;els.mobileWinner.textContent=winner;els.mobileOutputView.textContent=step.output||"아직 출력이 없습니다.";els.timeline.value=state.stepIndex;els.mobileTimeline.value=state.stepIndex;els.stepLabel.textContent=`${state.stepIndex+1} / ${state.steps.length}`;els.mobileTimelineStatus.textContent=`${state.stepIndex+1} / ${state.steps.length}`;els.prevBtn.disabled=els.mobilePrevBtn.disabled=state.stepIndex===0;els.nextBtn.disabled=els.mobileNextBtn.disabled=state.stepIndex===state.steps.length-1;if(follow){Core.centerInsideViewport(els.codeViewport,state.codeLines.get(step.line),{horizontal:false});Core.centerInsideViewport(els.mobileCodeViewport,state.mobileCodeLines.get(step.line),{horizontal:false});}}
  function stopPlayback(){if(state.timer)clearTimeout(state.timer);state.timer=null;Core.updatePlaybackControls(els.playBtn,false);}function goTo(i,o={}){state.stepIndex=Core.clamp(i,0,state.steps.length-1);render(o);}function move(d){stopPlayback();goTo(state.stepIndex+d,{follow:true});}function scheduleNext(){state.timer=setTimeout(()=>{if(state.stepIndex>=state.steps.length-1){stopPlayback();return;}goTo(state.stepIndex+1,{follow:true});state.stepIndex>=state.steps.length-1?stopPlayback():scheduleNext();},PROBLEM.autoplayMs/state.speed);}function startPlayback(){stopPlayback();if(state.stepIndex>=state.steps.length-1)goTo(0);Core.updatePlaybackControls(els.playBtn,true);scheduleNext();}function togglePlayback(){state.timer?stopPlayback():startPlayback();}function reset(){stopPlayback();goTo(0,{follow:true});}function renderSampleButtons(){els.sampleButtons.replaceChildren();samples.forEach(sample=>{const b=document.createElement("button");b.type="button";b.className="btn";b.textContent=sample.label;b.dataset.sample=sample.id;b.classList.toggle("selected",state.selectedSample===sample.id);els.sampleButtons.appendChild(b);});}
  function applyText(text,sampleId=null){stopPlayback();try{Object.assign(state,parseInput(text),{selectedSample:sampleId,stepIndex:0});els.inputError.textContent="";buildSteps();const max=Math.max(0,state.steps.length-1);els.timeline.max=els.mobileTimeline.max=max;renderSampleButtons();render({follow:true});}catch(error){els.inputError.textContent=error.message;}}
  els.prevBtn.addEventListener("click",()=>move(-1));els.nextBtn.addEventListener("click",()=>move(1));document.getElementById("mobilePlayBtn").addEventListener("click",()=>els.playBtn.click());els.mobilePrevBtn.addEventListener("click",()=>move(-1));els.mobileNextBtn.addEventListener("click",()=>move(1));els.resetBtn.addEventListener("click",reset);els.replayBtn.addEventListener("click",()=>{reset();startPlayback();});els.skipBtn.addEventListener("click",()=>{stopPlayback();goTo(state.steps.length-1,{follow:true});});els.playBtn.addEventListener("click",togglePlayback);els.speedRange.addEventListener("input",()=>{state.speed=Number(els.speedRange.value);els.speedLabel.textContent=`${Core.formatDecimal(state.speed)}×`;if(state.timer){clearTimeout(state.timer);scheduleNext();}});[els.timeline,els.mobileTimeline].forEach(t=>t.addEventListener("input",e=>{stopPlayback();goTo(Number(e.target.value),{follow:true});}));els.applyBtn.addEventListener("click",()=>applyText(els.inputArea.value));els.inputArea.addEventListener("input",()=>{state.selectedSample=null;renderSampleButtons();});els.sampleButtons.addEventListener("click",e=>{const b=e.target.closest("button[data-sample]");if(!b)return;const sample=samples.find(s=>s.id===b.dataset.sample);if(!sample)return;els.inputArea.value=sample.value;applyText(sample.value,sample.id);});
  renderCode();els.inputArea.value=defaultSample.value;applyText(defaultSample.value,defaultSample.id);
})();
