(() => {
  const Core = window.AlgoriZoomCore;
  const PROBLEM = Object.freeze({number:"5208",title:"전기버스2",autoplayMs:540,defaultSampleId:"all",maxFrames:4200,
    samples:[
      {id:"one",label:"샘플 1",value:"1\n5 2 3 1 1"},
      {id:"two",label:"샘플 2",value:"1\n10 2 1 3 2 2 5 4 2 1"},
      {id:"three",label:"샘플 3",value:"1\n10 1 1 2 1 2 2 1 2 1"},
      {id:"all",label:"전체 샘플",value:"3\n5 2 3 1 1\n10 2 1 3 2 2 5 4 2 1\n10 1 1 2 1 2 2 1 2 1"}
    ],
    sourceSteps:[
      {text:"def dfs(current, change):",types:"enter"},{text:"return",occurrence:1,types:"prune"},
      {text:"if ans <= change:",types:"checkPrune"},{text:"if current + M[current] >= N - 1:",types:"checkReach"},{text:"ans = min(ans, change)",types:"updateAns summary"},{text:"for i in range(current + M[current], current, -1):",types:"loop backtrack"},{text:"dfs(i, change + 1)",types:"recurse"},{text:"dfs(0, 0)",types:"start"},{text:"print('#{} {}'.format(tc, ans))",types:"output"}
    ]
  });
  const els=Core.getByIds(["sourceCode","codeView","mobileCodeView","codeViewport","mobileCodeViewport","resetBtn","prevBtn","nextBtn","playBtn","replayBtn","skipBtn","speedRange","speedLabel","timeline","mobileTimeline","stepLabel","mobileTimelineStatus","mobilePlayBtn","mobilePrevBtn","mobileNextBtn","codeLineLabel","mobileCodeStatus","board","mobileBoard","boardLabel","phaseLabel","mobilePhase","currentValue","changeValue","batteryValue","nextValue","ansValue","depthValue","explainText","mobileCoord","mobileExplanation","mobileStateMeta","mobileCurrent","mobileChange","mobileAns","mobileDepth","routeView","mobileRouteView","routeMeta","rangeView","mobileRangeView","outputView","mobileOutputView","inputArea","applyBtn","sampleButtons","inputError"]);
  const state={steps:[],stepIndex:0,timer:null,speed:1,selectedSample:PROBLEM.defaultSampleId}; let desktopLines,mobileLines,stepLines;
  function parseInput(text){const lines=text.trim().split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(!lines.length||!/^\d+$/.test(lines[0]))throw new Error("첫 줄에 T를 입력해주세요.");const T=Number(lines[0]);if(T<1||T>50)throw new Error("T는 1~50 사이여야 합니다.");if(lines.length!==T+1)throw new Error("각 테스트케이스는 한 줄에 N과 N-1개의 배터리 용량을 입력해주세요.");const cases=[];for(let tc=0;tc<T;tc++){const nums=lines[tc+1].split(/\s+/).map(Number);if(nums.some(Number.isNaN))throw new Error(`#${tc+1} 입력을 확인해주세요.`);const N=nums[0];if(!Number.isInteger(N)||N<3||N>100)throw new Error("N은 3~100 사이여야 합니다.");if(nums.length!==N)throw new Error(`#${tc+1}은 N과 N-1개의 배터리 용량, 총 ${N}개 숫자가 필요합니다.`);const M=nums.slice(1);if(M.some(v=>!Number.isInteger(v)||v<=0||v>=N))throw new Error("배터리 용량 Mi는 0 < Mi < N을 만족해야 합니다.");cases.push({N,M});}return cases;}
  function buildSteps(cases){const steps=[];let output="";const budget=Math.max(500,Math.floor(PROBLEM.maxFrames/cases.length));cases.forEach((data,ci)=>{let ans=Infinity,frames=0,omitted=false,calls=0;const seen=Array(data.N).fill(Infinity);const path=[];const push=(phase,current,change,message,extra={})=>{if(frames>=budget){omitted=true;return;}frames++;steps.push({tc:ci+1,data,phase,current,change,ans,path:[...path],message,output,...extra});};push("start",0,0,"출발 정류장에서 dfs(0, 0)을 시작합니다. 출발지의 배터리 장착은 교환 횟수에 포함하지 않습니다.");function dfs(current,change){calls++;path.push(current);push("enter",current,change,`정류장 ${current+1}에서 DFS를 시작합니다. 현재 교환 횟수는 ${change}회입니다.`);push("checkPrune",current,change,`ans(${Number.isFinite(ans)?ans:"∞"}) <= change(${change})인지 확인합니다.`);if(ans<=change){push("prune",current,change,"이미 찾은 최소 교환 횟수 이상이므로 이 경로를 가지치기합니다.",{pruned:true});path.pop();return;}if(seen[current]<=change){path.pop();return;}seen[current]=change;const reach=Math.min(data.N-1,current+data.M[current]);push("checkReach",current,change,`현재 배터리 용량은 ${data.M[current]}이므로 최대 ${reach+1}번 정류장까지 갈 수 있습니다. 목적지 ${data.N}번에 닿는지 확인합니다.`,{reach});if(reach>=data.N-1){const old=ans;ans=Math.min(ans,change);push("updateAns",current,change,`목적지까지 바로 갈 수 있습니다. ans를 ${Number.isFinite(old)?old:"∞"} → ${ans}로 갱신합니다.`,{reach,improved:ans<old});path.pop();return;}for(let i=reach;i>current;i--){push("loop",current,change,`${i+1}번 정류장을 다음 교환 위치 후보로 확인합니다. 먼 정류장부터 탐색합니다.`,{candidate:i,reach});push("recurse",current,change,`${i+1}번 정류장에서 배터리를 교환하고 dfs(${i}, ${change+1})을 호출합니다.`,{candidate:i,reach});dfs(i,change+1);push("backtrack",current,change,`${i+1}번 정류장 경로에서 돌아와 다음 후보를 확인합니다.`,{candidate:i,reach});}path.pop();}dfs(0,0);if(omitted)steps.push({tc:ci+1,data,phase:"summary",current:null,change:null,ans,path:[],message:`화면 단계는 ${budget}개까지만 표시했습니다. 계산은 끝까지 수행했으며 총 ${calls}회 DFS 호출 후 최소 교환 횟수 ${ans}회를 찾았습니다.`,output});output+=`#${ci+1} ${ans}\n`;steps.push({tc:ci+1,data,phase:"output",current:null,change:null,ans,path:[],message:`#${ci+1} ${ans}를 출력합니다.`,output});});return steps;}
  const names={start:"탐색 시작",enter:"DFS 호출",checkPrune:"가지치기 확인",prune:"가지치기",checkReach:"도달 범위 확인",updateAns:"정답 갱신",loop:"다음 정류장",recurse:"재귀 호출",backtrack:"호출 복귀",summary:"탐색 요약",output:"출력"};
  function board(container,s){const {N,M}=s.data;const reach=s.current==null?null:Math.min(N-1,s.current+M[s.current]);const path=new Set(s.path||[]);container.innerHTML=`<div class="bus-board"><div class="station-line">${Array.from({length:N},(_,i)=>{let cls="station";if(i===N-1)cls+=" destination";if(path.has(i))cls+=" path";if(reach!==null&&i>s.current&&i<=reach)cls+=" reachable";if(i===s.current)cls+=" current";if(i===s.candidate)cls+=" candidate";if(s.pruned&&i===s.current)cls+=" pruned";return `<div class="${cls}"><div class="station-dot">${i+1}</div><small>${i===N-1?"도착":"정류장"}</small><div class="cap">${i<N-1?`M=${M[i]}`:"배터리 없음"}</div></div>`}).join("")}</div><p class="bus-legend">파랑: 현재 배터리로 도달 가능 · 금색: 현재 정류장 · 초록: 다음 재귀 후보 · 보라/파랑: 현재 재귀 경로</p></div>`;}
  function route(container,s){if(!s.path.length){container.innerHTML='<span class="route-chip">경로 없음</span>';return;}container.innerHTML=s.path.map((v,i)=>`<span class="route-chip ${i===0?"start":"change"}">${v+1}번${i===0?" 출발":" 교환"}</span>`).join("");}
  function rangeText(s){if(s.current==null)return "탐색이 끝났습니다.";const r=Math.min(s.data.N-1,s.current+s.data.M[s.current]);return `${s.current+1}번 정류장 배터리 M=${s.data.M[s.current]} · 이동 가능 범위: ${s.current+2}번 ~ ${r+1}번 · 목적지: ${s.data.N}번`;}
  function highlight(lines,n){lines.forEach((line,k)=>line.classList.toggle("active",k===n));}
  function renderD(s){const ln=stepLines.get(s.phase);highlight(desktopLines,ln);board(els.board,s);route(els.routeView,s);els.codeLineLabel.textContent=ln?`LINE ${ln}`:names[s.phase];els.boardLabel.textContent=`#${s.tc} · N=${s.data.N}`;els.phaseLabel.textContent=names[s.phase];els.currentValue.textContent=s.current==null?"—":s.current;els.changeValue.textContent=s.change??"—";els.batteryValue.textContent=s.current==null?"—":s.data.M[s.current];els.nextValue.textContent=s.candidate==null?"—":s.candidate;els.ansValue.textContent=Number.isFinite(s.ans)?s.ans:"∞";els.depthValue.textContent=s.path.length;els.explainText.textContent=s.message;els.routeMeta.textContent=`깊이 ${s.path.length} · 교환 ${s.change??"—"}회`;els.rangeView.textContent=rangeText(s);els.outputView.textContent=s.output||"아직 출력이 없습니다.";}
  function renderM(s){const ln=stepLines.get(s.phase);highlight(mobileLines,ln);board(els.mobileBoard,s);route(els.mobileRouteView,s);els.mobileCoord.textContent=s.current==null?"탐색 완료":`current ${s.current}`;els.mobileCodeStatus.textContent=ln?`LINE ${ln}`:names[s.phase];els.mobilePhase.textContent=names[s.phase];els.mobileExplanation.textContent=s.message;els.mobileStateMeta.textContent=`#${s.tc} · N=${s.data.N}`;els.mobileCurrent.textContent=s.current??"—";els.mobileChange.textContent=s.change??"—";els.mobileAns.textContent=Number.isFinite(s.ans)?s.ans:"∞";els.mobileDepth.textContent=s.path.length;els.mobileRangeView.textContent=rangeText(s);els.mobileOutputView.textContent=s.output||"아직 출력이 없습니다.";}
  function sync(){const e=!state.steps.length;els.prevBtn.disabled=els.mobilePrevBtn.disabled=e||state.stepIndex===0;els.nextBtn.disabled=els.mobileNextBtn.disabled=e||state.stepIndex===state.steps.length-1;[els.playBtn,els.replayBtn,els.resetBtn,els.skipBtn,els.timeline,els.mobileTimeline,els.mobilePlayBtn].forEach(x=>x.disabled=e);}
  function render({follow=true}={}){const s=state.steps[state.stepIndex];if(!s)return;renderD(s);renderM(s);els.timeline.value=els.mobileTimeline.value=state.stepIndex;els.stepLabel.textContent=els.mobileTimelineStatus.textContent=`${state.stepIndex+1} / ${state.steps.length}`;sync();if(follow){const ln=stepLines.get(s.phase);if(ln){Core.centerInsideViewport(els.codeViewport,desktopLines.get(ln),{horizontal:false});Core.centerInsideViewport(els.mobileCodeViewport,mobileLines.get(ln),{horizontal:false});}}}
  function stop(){if(state.timer!==null)clearTimeout(state.timer);state.timer=null;Core.updatePlaybackControls(els.playBtn,false);}function go(i,o={}){if(!state.steps.length)return;state.stepIndex=Core.clamp(i,0,state.steps.length-1);render(o);}function move(d){stop();go(state.stepIndex+d);}function sched(){state.timer=setTimeout(()=>{if(state.stepIndex>=state.steps.length-1){stop();return;}go(state.stepIndex+1);if(state.stepIndex>=state.steps.length-1)stop();else sched();},PROBLEM.autoplayMs/state.speed);}function start(){if(!state.steps.length)return;stop();if(state.stepIndex>=state.steps.length-1)go(0);Core.updatePlaybackControls(els.playBtn,true);sched();}function reset(){stop();go(0);}
  function sampleButtons(){els.sampleButtons.replaceChildren();PROBLEM.samples.forEach(s=>{const b=document.createElement("button");b.type="button";b.className="btn";b.textContent=s.label;b.dataset.sample=s.id;b.classList.toggle("selected",state.selectedSample===s.id);els.sampleButtons.append(b);});}
  function apply(text,id=null){stop();try{state.steps=buildSteps(parseInput(text));state.stepIndex=0;state.selectedSample=id;els.inputError.textContent="";els.timeline.max=els.mobileTimeline.max=Math.max(0,state.steps.length-1);sampleButtons();render();}catch(e){state.selectedSample=null;els.inputError.textContent=e.message;sampleButtons();}}
  const markup=Core.createCodeMarkup(els.sourceCode,PROBLEM.sourceSteps,{wrap:false,editor:true});els.codeView.innerHTML=els.mobileCodeView.innerHTML=markup;desktopLines=Core.createLineMap(els.codeView);mobileLines=Core.createLineMap(els.mobileCodeView);stepLines=Core.createStepLineMap(els.codeView);
  els.prevBtn.onclick=()=>move(-1);els.nextBtn.onclick=()=>move(1);els.mobilePrevBtn.onclick=()=>move(-1);els.mobileNextBtn.onclick=()=>move(1);els.mobilePlayBtn.onclick=()=>els.playBtn.click();els.playBtn.onclick=()=>state.timer===null?start():stop();els.resetBtn.onclick=reset;els.replayBtn.onclick=()=>{reset();start();};els.skipBtn.onclick=()=>{stop();go(state.steps.length-1);};els.speedRange.oninput=()=>{state.speed=Number(els.speedRange.value);els.speedLabel.textContent=`${Core.formatDecimal(state.speed)}×`;if(state.timer!==null){clearTimeout(state.timer);sched();}};[els.timeline,els.mobileTimeline].forEach(x=>x.oninput=e=>{stop();go(Number(e.target.value));});els.applyBtn.onclick=()=>apply(els.inputArea.value);els.inputArea.oninput=()=>{state.selectedSample=null;sampleButtons();};els.sampleButtons.onclick=e=>{const b=e.target.closest("button[data-sample]");if(!b)return;const s=PROBLEM.samples.find(v=>v.id===b.dataset.sample);if(!s)return;els.inputArea.value=s.value;apply(s.value,s.id);};const d=PROBLEM.samples.find(s=>s.id===PROBLEM.defaultSampleId);sampleButtons();els.inputArea.value=d.value;apply(d.value,d.id);
})();
