(() => {
  const Core = window.AlgoriZoomCore;
  const PROBLEM = Object.freeze({ number:"5202", title:"화물 도크", autoplayMs:620, defaultSampleId:"all",
    samples:[
      {id:"one",label:"샘플 1",value:"1\n5\n20 23\n17 20\n23 24\n4 14\n8 18"},
      {id:"two",label:"샘플 2",value:"1\n10\n14 23\n2 19\n1 22\n12 24\n21 23\n6 15\n20 24\n1 4\n6 15\n15 16"},
      {id:"three",label:"샘플 3",value:"1\n15\n18 19\n2 7\n11 15\n13 16\n23 24\n2 14\n13 22\n20 23\n13 19\n7 15\n5 21\n20 24\n16 22\n17 21\n9 24"},
      {id:"all",label:"전체 샘플",value:"3\n5\n20 23\n17 20\n23 24\n4 14\n8 18\n10\n14 23\n2 19\n1 22\n12 24\n21 23\n6 15\n20 24\n1 4\n6 15\n15 16\n15\n18 19\n2 7\n11 15\n13 16\n23 24\n2 14\n13 22\n20 23\n13 19\n7 15\n5 21\n20 24\n16 22\n17 21\n9 24"}
    ],
    sourceSteps:[
      {text:"works = [tuple(map(int, input().split())) for _ in range(N)]",types:"input"},
      {text:"works.sort(key = lambda x:x[1])",types:"sort"},{text:"c_e = works[0][1]",types:"firstEnd"},{text:"truck = 1",types:"init"},{text:"for n_s, n_e in works[1:]:",types:"loop"},{text:"if n_s >= c_e:",types:"compare"},{text:"c_e = n_e",types:"updateEnd"},{text:"truck += 1",types:"select"},{text:"print('#{} {}'.format(tc, truck))",types:"output"}
    ]
  });
  const els=Core.getByIds(["sourceCode","codeView","mobileCodeView","codeViewport","mobileCodeViewport","resetBtn","prevBtn","nextBtn","playBtn","replayBtn","skipBtn","speedRange","speedLabel","timeline","mobileTimeline","stepLabel","mobileTimelineStatus","mobilePlayBtn","mobilePrevBtn","mobileNextBtn","codeLineLabel","mobileCodeStatus","board","mobileBoard","boardLabel","phaseLabel","mobilePhase","currentEndValue","nextStartValue","nextEndValue","truckValue","indexValue","remainingValue","explainText","mobileCoord","mobileExplanation","mobileStateMeta","mobileEnd","mobileStart","mobileNextEnd","mobileTruck","selectedView","mobileSelectedView","selectedMeta","outputView","mobileOutputView","inputArea","applyBtn","sampleButtons","inputError"]);
  const state={steps:[],stepIndex:0,timer:null,speed:1,selectedSample:PROBLEM.defaultSampleId}; let desktopLines,mobileLines,stepLines;
  function parseInput(text){const t=text.trim().split(/\s+/).filter(Boolean).map(Number);if(!t.length||t.some(Number.isNaN))throw new Error("숫자로 된 입력을 확인해주세요.");let c=0,T=t[c++],cases=[];if(!Number.isInteger(T)||T<1||T>50)throw new Error("T는 1~50 사이여야 합니다.");for(let tc=0;tc<T;tc++){let N=t[c++];if(!Number.isInteger(N)||N<1||N>100)throw new Error(`#${tc+1}의 N을 확인해주세요.`);let works=[];for(let i=0;i<N;i++){if(c+1>=t.length)throw new Error(`#${tc+1}의 작업 시간이 부족합니다.`);let s=t[c++],e=t[c++];if(!Number.isInteger(s)||!Number.isInteger(e)||s<0||s>=24||e<=0||e>24||s>=e)throw new Error("작업 시간은 0 ≤ s < e ≤ 24를 만족해야 합니다.");works.push([s,e]);}cases.push({N,works});}if(c!==t.length)throw new Error("입력 끝에 사용되지 않은 값이 있습니다.");return cases;}
  function buildSteps(cases){const steps=[];let output="";const push=d=>steps.push({...d,works:d.works.map(v=>[...v]),selected:d.selected.map(v=>[...v]),selectedIndices:[...(d.selectedIndices||[])],output});cases.forEach((item,ci)=>{let works=item.works.map(v=>[...v]),selected=[],selectedIndices=[],cEnd=null,nStart=null,nEnd=null,index=null,truck=0;const originalWorks=item.works.map(v=>[...v]);const base=(phase,message,extra={})=>push({tc:ci+1,N:item.N,works,selected,selectedIndices,cEnd,nStart,nEnd,index,truck,phase,message,...extra});base("input",`입력 순서대로 받은 작업 목록입니다: ${originalWorks.map(v=>`${v[0]}-${v[1]}`).join(", ")}`);works.sort((a,b)=>a[1]-b[1]);base("sort",`종료 시간이 빠른 순서로 정렬합니다: ${works.map(v=>`${v[0]}-${v[1]}`).join(", ")}`);cEnd=works[0][1];selected.push(works[0]);selectedIndices.push(0);base("firstEnd",`첫 작업 ${works[0][0]}-${works[0][1]}을 기준으로 현재 종료시간 c_e를 ${cEnd}로 둡니다.`,{current:0,accepted:true});truck=1;base("init","첫 작업을 이미 선택했으므로 truck을 1로 시작합니다.",{current:0,accepted:true});for(let i=1;i<works.length;i++){index=i;nStart=works[i][0];nEnd=works[i][1];base("loop",`${i}번 작업 ${nStart}-${nEnd}을 확인합니다.`,{current:i});const ok=nStart>=cEnd;base("compare",`${nStart} ≥ ${cEnd} → ${ok?"참. 앞 작업이 끝난 뒤 시작할 수 있습니다.":"거짓. 시간이 겹치므로 선택하지 않습니다."}`,{current:i,accepted:ok,rejected:!ok});if(ok){cEnd=nEnd;base("updateEnd",`이 작업을 선택하고 현재 종료시간 c_e를 ${nEnd}로 갱신합니다.`,{current:i,accepted:true});truck+=1;selected.push(works[i]);selectedIndices.push(i);base("select",`선택한 화물차 수를 ${truck}대로 늘립니다.`,{current:i,accepted:true});}}output+=`#${ci+1} ${truck}
`;base("output",`#${ci+1}의 최대 이용 차량 수 ${truck}대를 출력합니다.`);});return steps;}
  const names={input:"입력 순서",sort:"종료시간 정렬",firstEnd:"첫 작업 선택",init:"개수 초기화",loop:"다음 작업",compare:"시간 비교",updateEnd:"종료시간 갱신",select:"작업 선택",output:"출력"};
  function board(container,s){const chosen=s.selectedIndices||[];container.innerHTML=`<div class="dock-axis"><span>0시</span><span>6시</span><span>12시</span><span>18시</span><span>24시</span></div><div class="dock-list">${s.works.map((w,i)=>{let cls="dock-job";if(i===s.current)cls+=" current";if(s.phase!=="sort"&&chosen.includes(i)&&(i!==s.current||s.accepted))cls+=" accepted";if(i===s.current&&s.rejected)cls+=" rejected";if(s.index!==null&&i<s.index&&!chosen.includes(i))cls+=" past";return `<div class="${cls}"><span class="dock-label">#${i+1}</span><span class="dock-track"><span class="dock-bar" style="left:${w[0]/24*100}%;width:${(w[1]-w[0])/24*100}%"></span></span><span class="dock-time">${w[0]} → ${w[1]}</span></div>`}).join("")}</div><p class="dock-now">초록: 선택된 작업 · 흰 테두리: 현재 확인 · 빨강: 현재 종료시간과 겹쳐 선택 불가</p>`;}
  function selected(container,s){container.innerHTML=s.selected.length?s.selected.map((v,i)=>`<span class="selected-chip">${i+1}번째 · ${v[0]}시 → ${v[1]}시</span>`).join(""):'<span class="selected-empty">아직 선택한 작업이 없습니다.</span>';}
  function highlight(lines,n){lines.forEach((line,k)=>line.classList.toggle("active",k===n));}
  function renderD(s){let ln=stepLines.get(s.phase);highlight(desktopLines,ln);board(els.board,s);selected(els.selectedView,s);els.codeLineLabel.textContent=ln?`LINE ${ln}`:names[s.phase];els.boardLabel.textContent=`#${s.tc} · 신청 ${s.N}건`;els.phaseLabel.textContent=names[s.phase];els.currentEndValue.textContent=s.cEnd??"—";els.nextStartValue.textContent=s.nStart??"—";els.nextEndValue.textContent=s.nEnd??"—";els.truckValue.textContent=s.truck;els.indexValue.textContent=s.index??"—";els.remainingValue.textContent=s.index===null?s.works.length:Math.max(0,s.works.length-s.index-1);els.explainText.textContent=s.message;els.selectedMeta.textContent=`선택 ${s.selected.length}건`;els.outputView.textContent=s.output||"아직 출력이 없습니다.";}
  function renderM(s){let ln=stepLines.get(s.phase);highlight(mobileLines,ln);board(els.mobileBoard,s);selected(els.mobileSelectedView,s);els.mobileCoord.textContent=`#${s.tc} · truck = ${s.truck}`;els.mobileCodeStatus.textContent=ln?`LINE ${ln}`:names[s.phase];els.mobilePhase.textContent=names[s.phase];els.mobileExplanation.textContent=s.message;els.mobileStateMeta.textContent=`선택 ${s.selected.length}건`;els.mobileEnd.textContent=s.cEnd??"—";els.mobileStart.textContent=s.nStart??"—";els.mobileNextEnd.textContent=s.nEnd??"—";els.mobileTruck.textContent=s.truck;els.mobileOutputView.textContent=s.output||"아직 출력이 없습니다.";}
  function sync(){let e=!state.steps.length;els.prevBtn.disabled=els.mobilePrevBtn.disabled=e||state.stepIndex===0;els.nextBtn.disabled=els.mobileNextBtn.disabled=e||state.stepIndex===state.steps.length-1;[els.playBtn,els.replayBtn,els.resetBtn,els.skipBtn,els.timeline,els.mobileTimeline,els.mobilePlayBtn].forEach(x=>x.disabled=e)}
  function render({follow=true}={}){let s=state.steps[state.stepIndex];if(!s)return;renderD(s);renderM(s);els.timeline.value=els.mobileTimeline.value=state.stepIndex;els.stepLabel.textContent=els.mobileTimelineStatus.textContent=`${state.stepIndex+1} / ${state.steps.length}`;sync();if(follow){let ln=stepLines.get(s.phase);if(ln){Core.centerInsideViewport(els.codeViewport,desktopLines.get(ln),{horizontal:false});Core.centerInsideViewport(els.mobileCodeViewport,mobileLines.get(ln),{horizontal:false});}}}
  function stop(){if(state.timer!==null)clearTimeout(state.timer);state.timer=null;Core.updatePlaybackControls(els.playBtn,false)} function go(i,o={}){if(!state.steps.length)return;state.stepIndex=Core.clamp(i,0,state.steps.length-1);render(o)} function move(d){stop();go(state.stepIndex+d)} function sched(){state.timer=setTimeout(()=>{if(state.stepIndex>=state.steps.length-1){stop();return}go(state.stepIndex+1);if(state.stepIndex>=state.steps.length-1)stop();else sched()},PROBLEM.autoplayMs/state.speed)} function start(){if(!state.steps.length)return;stop();if(state.stepIndex>=state.steps.length-1)go(0);Core.updatePlaybackControls(els.playBtn,true);sched()} function reset(){stop();go(0)}
  function sampleButtons(){els.sampleButtons.replaceChildren();PROBLEM.samples.forEach(s=>{let b=document.createElement("button");b.type="button";b.className="btn";b.textContent=s.label;b.dataset.sample=s.id;b.classList.toggle("selected",state.selectedSample===s.id);els.sampleButtons.append(b)})}
  function apply(text,id=null){stop();try{state.steps=buildSteps(parseInput(text));state.stepIndex=0;state.selectedSample=id;els.inputError.textContent="";els.timeline.max=els.mobileTimeline.max=Math.max(0,state.steps.length-1);sampleButtons();render()}catch(e){state.selectedSample=null;els.inputError.textContent=e.message;sampleButtons()}}
  const markup=Core.createCodeMarkup(els.sourceCode,PROBLEM.sourceSteps,{wrap:false,editor:true});els.codeView.innerHTML=els.mobileCodeView.innerHTML=markup;desktopLines=Core.createLineMap(els.codeView);mobileLines=Core.createLineMap(els.mobileCodeView);stepLines=Core.createStepLineMap(els.codeView);
  els.prevBtn.onclick=()=>move(-1);els.nextBtn.onclick=()=>move(1);els.mobilePrevBtn.onclick=()=>move(-1);els.mobileNextBtn.onclick=()=>move(1);els.mobilePlayBtn.onclick=()=>els.playBtn.click();els.playBtn.onclick=()=>state.timer===null?start():stop();els.resetBtn.onclick=reset;els.replayBtn.onclick=()=>{reset();start()};els.skipBtn.onclick=()=>{stop();go(state.steps.length-1)};els.speedRange.oninput=()=>{state.speed=Number(els.speedRange.value);els.speedLabel.textContent=`${Core.formatDecimal(state.speed)}×`;if(state.timer!==null){clearTimeout(state.timer);sched()}};[els.timeline,els.mobileTimeline].forEach(x=>x.oninput=e=>{stop();go(Number(e.target.value))});els.applyBtn.onclick=()=>apply(els.inputArea.value);els.inputArea.oninput=()=>{state.selectedSample=null;sampleButtons()};els.sampleButtons.onclick=e=>{let b=e.target.closest("button[data-sample]");if(!b)return;let s=PROBLEM.samples.find(v=>v.id===b.dataset.sample);if(!s)return;els.inputArea.value=s.value;apply(s.value,s.id)};let d=PROBLEM.samples.find(s=>s.id===PROBLEM.defaultSampleId);sampleButtons();els.inputArea.value=d.value;apply(d.value,d.id);
})();
