(() => {
  const Core=window.AlgoriZoomCore;
  const PROBLEM=Object.freeze({number:"5203",title:"베이비진 게임",autoplayMs:560,defaultSampleId:"all",samples:[
    {id:"one",label:"샘플 1",value:"1\n9 9 5 6 5 6 1 1 4 2 2 1"},{id:"two",label:"샘플 2",value:"1\n5 3 2 9 1 5 2 0 9 2 0 0"},{id:"three",label:"샘플 3",value:"1\n2 8 7 7 0 2 2 2 5 4 0 3"},{id:"all",label:"전체 샘플",value:"3\n9 9 5 6 5 6 1 1 4 2 2 1\n5 3 2 9 1 5 2 0 9 2 0 0\n2 8 7 7 0 2 2 2 5 4 0 3"}],sourceSteps:[
      {text:"player.sort()",types:"sortHand"},{text:"run_player = sorted(set(player))",types:"unique"},{text:"for j in range(len(run_player)-2):",types:"runLoop"},{text:"if run_player[j] + 1 == run_player[j+1] and run_player[j+1] + 1 == run_player[j+2]:",types:"runCheck"},{text:"return True",types:"runWin",occurrence:1},{text:"for j in range(len(player)-2):",types:"tripLoop"},{text:"if player[j] == player[j+1] == player[j+2]:",types:"tripCheck"},{text:"return True",types:"tripWin",occurrence:2},{text:"return False",types:"falseReturn"},{text:"ans = 0",types:"init"},{text:"for i in range(len(cards)):",types:"draw"},{text:"if i % 2 == 0:",types:"turn"},{text:"first.append(cards[i])",types:"append1"},{text:"if check(first):",types:"check1"},{text:"ans = 1",types:"win1"},{text:"second.append(cards[i])",types:"append2"},{text:"if check(second):",types:"check2"},{text:"ans = 2",types:"win2"},{text:"print('#{} {}'.format(tc, ans))",types:"output"}
  ]});
  const els=Core.getByIds(["sourceCode","codeView","mobileCodeView","codeViewport","mobileCodeViewport","resetBtn","prevBtn","nextBtn","playBtn","replayBtn","skipBtn","speedRange","speedLabel","timeline","mobileTimeline","stepLabel","mobileTimelineStatus","mobilePlayBtn","mobilePrevBtn","mobileNextBtn","codeLineLabel","mobileCodeStatus","board","mobileBoard","boardLabel","phaseLabel","mobilePhase","indexValue","cardValue","playerValue","checkIndexValue","patternValue","ansValue","explainText","mobileCoord","mobileExplanation","mobileStateMeta","mobileIndex","mobileCard","mobilePlayer","mobileAns","handView","mobileHandView","resultMeta","outputView","mobileOutputView","inputArea","applyBtn","sampleButtons","inputError"]);
  const state={steps:[],stepIndex:0,timer:null,speed:1,selectedSample:PROBLEM.defaultSampleId};let desktopLines,mobileLines,stepLines;
  function parseInput(text){const t=text.trim().split(/\s+/).filter(Boolean).map(Number);if(!t.length||t.some(Number.isNaN))throw new Error("숫자로 된 입력을 확인해주세요.");let c=0,T=t[c++],cases=[];if(!Number.isInteger(T)||T<1||T>50)throw new Error("T는 1~50 사이여야 합니다.");for(let tc=0;tc<T;tc++){if(c+12>t.length)throw new Error(`#${tc+1}의 카드 12장이 부족합니다.`);let cards=t.slice(c,c+12);c+=12;if(cards.some(v=>!Number.isInteger(v)||v<0||v>9))throw new Error("카드는 0~9 사이 정수여야 합니다.");cases.push({cards});}if(c!==t.length)throw new Error("입력 끝에 사용되지 않은 값이 있습니다.");return cases;}
  function checkSteps(hand,base,playerNo){hand.sort((a,b)=>a-b);base("sortHand",`플레이어 ${playerNo}의 카드를 정렬합니다: ${hand.join(", ")}`,{activePlayer:playerNo});const uniq=[...new Set(hand)];base("unique",`run 검사를 위해 중복을 제거합니다: ${uniq.join(", ")||"없음"}`,{activePlayer:playerNo,unique:uniq});for(let j=0;j<uniq.length-2;j++){base("runLoop",`run 후보 ${uniq[j]}, ${uniq[j+1]}, ${uniq[j+2]}을 확인합니다.`,{activePlayer:playerNo,j,unique:uniq});let ok=uniq[j]+1===uniq[j+1]&&uniq[j+1]+1===uniq[j+2];base("runCheck",`${uniq[j]}, ${uniq[j+1]}, ${uniq[j+2]} → ${ok?"연속된 3장입니다.":"run이 아닙니다."}`,{activePlayer:playerNo,j,unique:uniq,pattern:ok?"RUN":"—",patternCards:ok?[uniq[j],uniq[j+1],uniq[j+2]]:[]});if(ok){base("runWin",`플레이어 ${playerNo}가 run을 완성했습니다.`,{activePlayer:playerNo,j,pattern:"RUN",patternCards:[uniq[j],uniq[j+1],uniq[j+2]]});return true;}}
    for(let j=0;j<hand.length-2;j++){base("tripLoop",`triplet 후보 ${hand[j]}, ${hand[j+1]}, ${hand[j+2]}을 확인합니다.`,{activePlayer:playerNo,j});let ok=hand[j]===hand[j+1]&&hand[j+1]===hand[j+2];base("tripCheck",`${hand[j]}, ${hand[j+1]}, ${hand[j+2]} → ${ok?"같은 숫자 3장입니다.":"triplet이 아닙니다."}`,{activePlayer:playerNo,j,pattern:ok?"TRIPLET":"—",patternCards:ok?[hand[j],hand[j+1],hand[j+2]]:[]});if(ok){base("tripWin",`플레이어 ${playerNo}가 triplet을 완성했습니다.`,{activePlayer:playerNo,j,pattern:"TRIPLET",patternCards:[hand[j],hand[j+1],hand[j+2]]});return true;}}
    base("falseReturn",`플레이어 ${playerNo}는 아직 run이나 triplet이 없습니다.`,{activePlayer:playerNo});return false;}
  function buildSteps(cases){const steps=[];let output="";const push=d=>steps.push({...d,cards:[...d.cards],first:[...d.first],second:[...d.second],patternCards:[...(d.patternCards||[])],output});cases.forEach((item,ci)=>{let cards=[...item.cards],first=[],second=[],ans=0,i=null,currentCard=null,activePlayer=null,j=null,pattern="—";const base=(phase,message,extra={})=>push({tc:ci+1,cards,first,second,ans,i,currentCard,activePlayer,j,pattern,phase,message,...extra});base("init","승자가 아직 없으므로 ans = 0으로 시작합니다.");for(i=0;i<cards.length;i++){currentCard=cards[i];activePlayer=i%2===0?1:2;j=null;pattern="—";base("draw",`${i+1}번째 카드 ${currentCard}을 가져올 차례입니다.`,{dealtCount:i});base("turn",`i = ${i}이므로 플레이어 ${activePlayer}의 차례입니다.`,{dealtCount:i});if(activePlayer===1){first.push(currentCard);base("append1",`플레이어 1이 카드 ${currentCard}을 받습니다.`,{dealtCount:i+1});let won=checkSteps(first,base,1);base("check1",`플레이어 1의 패를 검사한 결과: ${won?"Baby-gin 완성":"아직 완성되지 않음"}`,{dealtCount:i+1,pattern:won?steps[steps.length-1].pattern:"—",patternCards:won?steps[steps.length-1].patternCards:[]});if(won){ans=1;base("win1","플레이어 1이 먼저 완성했으므로 ans = 1로 정하고 게임을 종료합니다.",{dealtCount:i+1,pattern:steps[steps.length-1].pattern,patternCards:steps[steps.length-1].patternCards});break;}}else{second.push(currentCard);base("append2",`플레이어 2가 카드 ${currentCard}을 받습니다.`,{dealtCount:i+1});let won=checkSteps(second,base,2);base("check2",`플레이어 2의 패를 검사한 결과: ${won?"Baby-gin 완성":"아직 완성되지 않음"}`,{dealtCount:i+1,pattern:won?steps[steps.length-1].pattern:"—",patternCards:won?steps[steps.length-1].patternCards:[]});if(won){ans=2;base("win2","플레이어 2가 먼저 완성했으므로 ans = 2로 정하고 게임을 종료합니다.",{dealtCount:i+1,pattern:steps[steps.length-1].pattern,patternCards:steps[steps.length-1].patternCards});break;}}}
      output+=`#${ci+1} ${ans}\n`;base("output",ans===0?`#${ci+1}은 두 플레이어 모두 완성하지 못해 0을 출력합니다.`:`#${ci+1}의 승자 플레이어 ${ans}을 출력합니다.`,{dealtCount:ans?i+1:12});});return steps;}
  const names={sortHand:"패 정렬",unique:"중복 제거",runLoop:"run 후보",runCheck:"run 검사",runWin:"run 완성",tripLoop:"triplet 후보",tripCheck:"triplet 검사",tripWin:"triplet 완성",falseReturn:"미완성",init:"초기화",draw:"카드 확인",turn:"플레이어 차례",append1:"P1 카드 추가",check1:"P1 판정",win1:"P1 승리",append2:"P2 카드 추가",check2:"P2 판정",win2:"P2 승리",output:"출력"};
  function cardsHtml(arr,cls,patternCards=[]){let counts={};patternCards.forEach(v=>counts[v]=(counts[v]||0)+1);return arr.map(v=>{let p=counts[v]>0;if(p)counts[v]--;return `<span class="game-card ${cls}${p?" pattern":""}">${v}</span>`}).join("")||'<span class="pattern-note">아직 카드 없음</span>';}
  function board(container,s){let dealt=s.dealtCount??0;container.innerHTML=`<p class="deck-title"><span>카드 순서</span><span>${dealt} / 12장 분배</span></p><div class="card-row">${s.cards.map((v,i)=>`<span class="game-card${i<dealt?" dealt":""}${i===s.i&&i>=dealt?" current":""}">${v}</span>`).join("")}</div><div class="players-grid"><div class="player-box"><p class="player-title"><span>PLAYER 1</span><span>${s.first.length}장</span></p><div class="card-row">${cardsHtml(s.first,"p1",s.activePlayer===1?s.patternCards:[])}</div></div><div class="player-box"><p class="player-title"><span>PLAYER 2</span><span>${s.second.length}장</span></p><div class="card-row">${cardsHtml(s.second,"p2",s.activePlayer===2?s.patternCards:[])}</div></div></div><p class="pattern-note">초록 테두리: 현재 run/triplet을 만든 카드 · 흐린 카드: 이미 분배된 카드</p>`;}
  function hands(container,s){container.innerHTML=`<div class="hand-summary"><strong>PLAYER 1</strong><span>${s.first.length?s.first.join(" · "):"—"}</span></div><div class="hand-summary"><strong>PLAYER 2</strong><span>${s.second.length?s.second.join(" · "):"—"}</span></div>`;}
  function highlight(lines,n){lines.forEach((line,k)=>line.classList.toggle("active",k===n));}
  function renderD(s){let ln=stepLines.get(s.phase);highlight(desktopLines,ln);board(els.board,s);hands(els.handView,s);els.codeLineLabel.textContent=ln?`LINE ${ln}`:names[s.phase];els.boardLabel.textContent=`#${s.tc} · ${s.dealtCount??0}/12장`;els.phaseLabel.textContent=names[s.phase];els.indexValue.textContent=s.i??"—";els.cardValue.textContent=s.currentCard??"—";els.playerValue.textContent=s.activePlayer?`P${s.activePlayer}`:"—";els.checkIndexValue.textContent=s.j??"—";els.patternValue.textContent=s.pattern||"—";els.ansValue.textContent=s.ans;els.explainText.textContent=s.message;els.resultMeta.textContent=s.ans?`PLAYER ${s.ans} 승리`:s.phase==="output"?"무승부":"게임 진행 중";els.outputView.textContent=s.output||"아직 출력이 없습니다.";}
  function renderM(s){let ln=stepLines.get(s.phase);highlight(mobileLines,ln);board(els.mobileBoard,s);hands(els.mobileHandView,s);els.mobileCoord.textContent=`#${s.tc} · ans = ${s.ans}`;els.mobileCodeStatus.textContent=ln?`LINE ${ln}`:names[s.phase];els.mobilePhase.textContent=names[s.phase];els.mobileExplanation.textContent=s.message;els.mobileStateMeta.textContent=s.ans?`PLAYER ${s.ans} 승리`:s.phase==="output"?"무승부":s.pattern&&s.pattern!=="—"?s.pattern:"카드 분배";els.mobileIndex.textContent=s.i??"—";els.mobileCard.textContent=s.currentCard??"—";els.mobilePlayer.textContent=s.activePlayer?`P${s.activePlayer}`:"—";els.mobileAns.textContent=s.ans;els.mobileOutputView.textContent=s.output||"아직 출력이 없습니다.";}
  function sync(){let e=!state.steps.length;els.prevBtn.disabled=els.mobilePrevBtn.disabled=e||state.stepIndex===0;els.nextBtn.disabled=els.mobileNextBtn.disabled=e||state.stepIndex===state.steps.length-1;[els.playBtn,els.replayBtn,els.resetBtn,els.skipBtn,els.timeline,els.mobileTimeline,els.mobilePlayBtn].forEach(x=>x.disabled=e)}
  function render({follow=true}={}){let s=state.steps[state.stepIndex];if(!s)return;renderD(s);renderM(s);els.timeline.value=els.mobileTimeline.value=state.stepIndex;els.stepLabel.textContent=els.mobileTimelineStatus.textContent=`${state.stepIndex+1} / ${state.steps.length}`;sync();if(follow){let ln=stepLines.get(s.phase);if(ln){Core.centerInsideViewport(els.codeViewport,desktopLines.get(ln),{horizontal:false});Core.centerInsideViewport(els.mobileCodeViewport,mobileLines.get(ln),{horizontal:false});}}}
  function stop(){if(state.timer!==null)clearTimeout(state.timer);state.timer=null;Core.updatePlaybackControls(els.playBtn,false)}function go(i,o={}){if(!state.steps.length)return;state.stepIndex=Core.clamp(i,0,state.steps.length-1);render(o)}function move(d){stop();go(state.stepIndex+d)}function sched(){state.timer=setTimeout(()=>{if(state.stepIndex>=state.steps.length-1){stop();return}go(state.stepIndex+1);if(state.stepIndex>=state.steps.length-1)stop();else sched()},PROBLEM.autoplayMs/state.speed)}function start(){if(!state.steps.length)return;stop();if(state.stepIndex>=state.steps.length-1)go(0);Core.updatePlaybackControls(els.playBtn,true);sched()}function reset(){stop();go(0)}
  function sampleButtons(){els.sampleButtons.replaceChildren();PROBLEM.samples.forEach(s=>{let b=document.createElement("button");b.type="button";b.className="btn";b.textContent=s.label;b.dataset.sample=s.id;b.classList.toggle("selected",state.selectedSample===s.id);els.sampleButtons.append(b)})}
  function apply(text,id=null){stop();try{state.steps=buildSteps(parseInput(text));state.stepIndex=0;state.selectedSample=id;els.inputError.textContent="";els.timeline.max=els.mobileTimeline.max=Math.max(0,state.steps.length-1);sampleButtons();render()}catch(e){state.selectedSample=null;els.inputError.textContent=e.message;sampleButtons()}}
  const markup=Core.createCodeMarkup(els.sourceCode,PROBLEM.sourceSteps,{wrap:false,editor:true});els.codeView.innerHTML=els.mobileCodeView.innerHTML=markup;desktopLines=Core.createLineMap(els.codeView);mobileLines=Core.createLineMap(els.mobileCodeView);stepLines=Core.createStepLineMap(els.codeView);
  els.prevBtn.onclick=()=>move(-1);els.nextBtn.onclick=()=>move(1);els.mobilePrevBtn.onclick=()=>move(-1);els.mobileNextBtn.onclick=()=>move(1);els.mobilePlayBtn.onclick=()=>els.playBtn.click();els.playBtn.onclick=()=>state.timer===null?start():stop();els.resetBtn.onclick=reset;els.replayBtn.onclick=()=>{reset();start()};els.skipBtn.onclick=()=>{stop();go(state.steps.length-1)};els.speedRange.oninput=()=>{state.speed=Number(els.speedRange.value);els.speedLabel.textContent=`${Core.formatDecimal(state.speed)}×`;if(state.timer!==null){clearTimeout(state.timer);sched()}};[els.timeline,els.mobileTimeline].forEach(x=>x.oninput=e=>{stop();go(Number(e.target.value))});els.applyBtn.onclick=()=>apply(els.inputArea.value);els.inputArea.oninput=()=>{state.selectedSample=null;sampleButtons()};els.sampleButtons.onclick=e=>{let b=e.target.closest("button[data-sample]");if(!b)return;let s=PROBLEM.samples.find(v=>v.id===b.dataset.sample);if(!s)return;els.inputArea.value=s.value;apply(s.value,s.id)};let d=PROBLEM.samples.find(s=>s.id===PROBLEM.defaultSampleId);sampleButtons();els.inputArea.value=d.value;apply(d.value,d.id);
})();
