(() => {
  const Core=window.AlgoriZoomCore;
  const PROBLEM=Object.freeze({number:"5209",title:"최소 생산 비용",autoplayMs:520,defaultSampleId:"all",maxFrames:4800,
    samples:[
      {id:"one",label:"샘플 1",value:"1\n3\n73 21 21\n11 59 40\n24 31 83"},
      {id:"two",label:"샘플 2",value:"1\n5\n93 4 65 31 66\n63 12 60 60 84\n87 57 44 35 20\n12 9 40 12 40\n60 21 3 49 54"},
      {id:"three",label:"샘플 3",value:"1\n6\n55 83 32 79 53 70\n77 88 80 93 42 29\n54 26 5 10 25 94\n77 92 82 83 11 51\n84 11 21 62 45 58\n37 88 13 34 41 4"},
      {id:"all",label:"전체 샘플",value:"3\n3\n73 21 21\n11 59 40\n24 31 83\n5\n93 4 65 31 66\n63 12 60 60 84\n87 57 44 35 20\n12 9 40 12 40\n60 21 3 49 54\n6\n55 83 32 79 53 70\n77 88 80 93 42 29\n54 26 5 10 25 94\n77 92 82 83 11 51\n84 11 21 62 45 58\n37 88 13 34 41 4"}
    ],sourceSteps:[
      {text:"if cost >= ans:",types:"checkCost"},{text:"if product == N:",types:"complete"},{text:"ans = min(ans, cost)",types:"updateAns"},{text:"for i in range(N):",types:"loop"},{text:"if not used[i]:",types:"checkUsed"},{text:"used[i] = True",types:"use"},{text:"dfs(product + 1, cost + factory[product][i])",types:"recurse"},{text:"used[i] = False",types:"backtrack"},{text:"dfs(0, 0)",types:"start"},{text:"print('#{} {}'.format(tc, ans))",types:"output"}
    ]});
  const els=Core.getByIds(["sourceCode","codeView","mobileCodeView","codeViewport","mobileCodeViewport","resetBtn","prevBtn","nextBtn","playBtn","replayBtn","skipBtn","speedRange","speedLabel","timeline","mobileTimeline","stepLabel","mobileTimelineStatus","mobilePlayBtn","mobilePrevBtn","mobileNextBtn","codeLineLabel","mobileCodeStatus","board","mobileBoard","boardLabel","phaseLabel","mobilePhase","productValue","costValue","factoryValue","pickCostValue","ansValue","usedCountValue","explainText","mobileCoord","mobileExplanation","mobileStateMeta","mobileProduct","mobileCost","mobileAns","mobileUsed","assignView","mobileAssignView","assignMeta","costBreakdown","mobileCostBreakdown","outputView","mobileOutputView","inputArea","applyBtn","sampleButtons","inputError"]);
  const state={steps:[],stepIndex:0,timer:null,speed:1,selectedSample:PROBLEM.defaultSampleId};let desktopLines,mobileLines,stepLines;
  function parseInput(text){const t=text.trim().split(/\s+/).filter(Boolean).map(Number);if(!t.length||t.some(Number.isNaN))throw new Error("숫자로 된 입력을 확인해주세요.");let c=0,T=t[c++],cases=[];if(!Number.isInteger(T)||T<1||T>50)throw new Error("T는 1~50 사이여야 합니다.");for(let tc=0;tc<T;tc++){const N=t[c++];if(!Number.isInteger(N)||N<3||N>15)throw new Error(`#${tc+1}의 N은 3~15 사이여야 합니다.`);const factory=[];for(let r=0;r<N;r++){const row=[];for(let col=0;col<N;col++){if(c>=t.length)throw new Error(`#${tc+1}의 비용표 값이 부족합니다.`);const v=t[c++];if(!Number.isInteger(v)||v<1||v>99)throw new Error("생산비용은 1~99 사이의 정수여야 합니다.");row.push(v);}factory.push(row);}cases.push({N,factory});}if(c!==t.length)throw new Error("입력 끝에 사용되지 않은 값이 있습니다.");return cases;}
  function buildSteps(cases){const steps=[];let output="";const budget=Math.max(700,Math.floor(PROBLEM.maxFrames/cases.length));cases.forEach((data,ci)=>{const {N,factory}=data;let ans=Infinity,frames=0,omitted=false,calls=0;const used=Array(N).fill(false),assign=[],memo=new Map();const push=(phase,product,cost,message,extra={})=>{if(frames>=budget){omitted=true;return;}frames++;steps.push({tc:ci+1,data,phase,product,cost,ans,used:[...used],assign:assign.map(v=>({...v})),message,output,...extra});};push("start",0,0,"제품 1부터 공장을 하나씩 배정하기 위해 dfs(0, 0)을 시작합니다.");function dfs(product,cost,mask){calls++;push("enter",product,cost,`제품 ${product+1} 배정을 시작합니다. 현재 누적 비용은 ${cost}입니다.`);push("checkCost",product,cost,`cost(${cost}) >= ans(${Number.isFinite(ans)?ans:"∞"})인지 확인합니다.`);if(cost>=ans){push("pruneCost",product,cost,"현재 비용이 이미 최소 비용 이상이므로 더 내려가지 않고 가지치기합니다.",{pruned:true});return;}const prev=memo.get(mask);if(prev!==undefined&&prev<=cost)return;memo.set(mask,cost);push("complete",product,cost,product===N?"모든 제품의 공장 배정이 끝났습니다. ans를 갱신합니다.":`아직 ${N-product}개 제품이 남았습니다.`);if(product===N){const old=ans;ans=Math.min(ans,cost);push("updateAns",product,cost,`ans를 ${Number.isFinite(old)?old:"∞"} → ${ans}로 갱신합니다.`,{improved:ans<old});return;}for(let i=0;i<N;i++){push("loop",product,cost,`제품 ${product+1}에 공장 ${i+1}을 배정할 수 있는지 확인합니다.`,{candidate:i});push("checkUsed",product,cost,`used[${i}]는 ${used[i]}. ${used[i]?"이미 사용한 공장이므로 건너뜁니다.":"사용하지 않은 공장이므로 선택할 수 있습니다."}`,{candidate:i});if(!used[i]){used[i]=true;const add=factory[product][i];assign.push({product,factory:i,cost:add});push("use",product,cost,`공장 ${i+1}을 사용 처리하고 제품 ${product+1}의 비용 ${add}를 선택합니다.`,{candidate:i,pickCost:add});push("recurse",product,cost,`dfs(${product+1}, ${cost}+${add}) → 누적 비용 ${cost+add}로 다음 제품을 탐색합니다.`,{candidate:i,pickCost:add});dfs(product+1,cost+add,mask|(1<<i));assign.pop();used[i]=false;push("backtrack",product,cost,`재귀에서 돌아와 used[${i}]를 False로 복구합니다.`,{candidate:i,pickCost:add});}}}dfs(0,0,0);if(omitted){steps.push({tc:ci+1,data,phase:"summary",product:null,cost:null,ans,used:Array(N).fill(false),assign:[],message:`화면 단계는 ${budget}개까지만 표시했습니다. 계산은 끝까지 수행했으며 ${calls}회 상태를 확인해 최소 비용 ${ans}를 찾았습니다.`,output});}output+=`#${ci+1} ${ans}\n`;steps.push({tc:ci+1,data,phase:"output",product:null,cost:null,ans,used:Array(N).fill(false),assign:[],message:`#${ci+1} ${ans}를 출력합니다.`,output});});return steps;}
  const names={start:"탐색 시작",enter:"DFS 호출",checkCost:"비용 가지치기",pruneCost:"가지치기",complete:"완료 확인",updateAns:"정답 갱신",loop:"공장 반복",checkUsed:"사용 여부 확인",use:"공장 선택",recurse:"재귀 호출",backtrack:"사용 복구",summary:"탐색 요약",output:"출력"};
  function board(container,s){const {N,factory}=s.data;const assigned=new Map(s.assign.map(v=>[v.product,v.factory]));container.innerHTML=`<table class="factory-table"><thead><tr><th>제품 ↓ / 공장 →</th>${Array.from({length:N},(_,i)=>`<th>공장 ${i+1}</th>`).join("")}</tr></thead><tbody>${factory.map((row,r)=>`<tr class="${r===s.product?"current-row":""}"><th>제품 ${r+1}</th>${row.map((v,c)=>{let cls="";if(s.used[c])cls+=" used-col";if(assigned.get(r)===c)cls+=" assigned";if(r===s.product&&c===s.candidate)cls+=s.phase==="use"||s.phase==="recurse"?" pick":" candidate";if(s.pruned&&r===s.product&&c===s.candidate)cls+=" pruned";return `<td class="${cls.trim()}">${v}</td>`}).join("")}</tr>`).join("")}</tbody></table><p class="matrix-legend">파랑: 현재까지 확정한 배정 · 흐림: 이미 사용 중인 공장 · 금색: 현재 확인 중인 후보 · 초록: 방금 선택한 비용</p>`;}
  function assignments(container,s){container.innerHTML=s.assign.length?s.assign.map(v=>`<span class="assign-chip">제품 ${v.product+1} → 공장 ${v.factory+1} <strong>+${v.cost}</strong></span>`).join(""):'<span class="assign-chip">아직 배정된 제품이 없습니다.</span>';}
  function breakdown(s){if(!s.assign.length)return `현재 누적 비용: ${s.cost??0} · ans: ${Number.isFinite(s.ans)?s.ans:"∞"}`;return `${s.assign.map(v=>v.cost).join(" + ")} = ${s.assign.reduce((a,v)=>a+v.cost,0)} · ans: ${Number.isFinite(s.ans)?s.ans:"∞"}`;}
  function highlight(lines,n){lines.forEach((line,k)=>line.classList.toggle("active",k===n));}
  function renderD(s){const ln=stepLines.get(s.phase);highlight(desktopLines,ln);board(els.board,s);assignments(els.assignView,s);els.codeLineLabel.textContent=ln?`LINE ${ln}`:names[s.phase];els.boardLabel.textContent=`#${s.tc} · N=${s.data.N}`;els.phaseLabel.textContent=names[s.phase];els.productValue.textContent=s.product??"—";els.costValue.textContent=s.cost??"—";els.factoryValue.textContent=s.candidate==null?"—":s.candidate;els.pickCostValue.textContent=s.pickCost??"—";els.ansValue.textContent=Number.isFinite(s.ans)?s.ans:"∞";els.usedCountValue.textContent=s.used.filter(Boolean).length;els.explainText.textContent=s.message;els.assignMeta.textContent=`${s.assign.length} / ${s.data.N} 제품 배정`;els.costBreakdown.textContent=breakdown(s);els.outputView.textContent=s.output||"아직 출력이 없습니다.";}
  function renderM(s){const ln=stepLines.get(s.phase);highlight(mobileLines,ln);board(els.mobileBoard,s);assignments(els.mobileAssignView,s);els.mobileCoord.textContent=s.product==null?"탐색 완료":`product ${s.product}`;els.mobileCodeStatus.textContent=ln?`LINE ${ln}`:names[s.phase];els.mobilePhase.textContent=names[s.phase];els.mobileExplanation.textContent=s.message;els.mobileStateMeta.textContent=`#${s.tc} · N=${s.data.N}`;els.mobileProduct.textContent=s.product??"—";els.mobileCost.textContent=s.cost??"—";els.mobileAns.textContent=Number.isFinite(s.ans)?s.ans:"∞";els.mobileUsed.textContent=s.used.filter(Boolean).length;els.mobileCostBreakdown.textContent=breakdown(s);els.mobileOutputView.textContent=s.output||"아직 출력이 없습니다.";}
  function sync(){const e=!state.steps.length;els.prevBtn.disabled=els.mobilePrevBtn.disabled=e||state.stepIndex===0;els.nextBtn.disabled=els.mobileNextBtn.disabled=e||state.stepIndex===state.steps.length-1;[els.playBtn,els.replayBtn,els.resetBtn,els.skipBtn,els.timeline,els.mobileTimeline,els.mobilePlayBtn].forEach(x=>x.disabled=e);}
  function render({follow=true}={}){const s=state.steps[state.stepIndex];if(!s)return;renderD(s);renderM(s);els.timeline.value=els.mobileTimeline.value=state.stepIndex;els.stepLabel.textContent=els.mobileTimelineStatus.textContent=`${state.stepIndex+1} / ${state.steps.length}`;sync();if(follow){const ln=stepLines.get(s.phase);if(ln){Core.centerInsideViewport(els.codeViewport,desktopLines.get(ln),{horizontal:false});Core.centerInsideViewport(els.mobileCodeViewport,mobileLines.get(ln),{horizontal:false});}}}
  function stop(){if(state.timer!==null)clearTimeout(state.timer);state.timer=null;Core.updatePlaybackControls(els.playBtn,false);}function go(i,o={}){if(!state.steps.length)return;state.stepIndex=Core.clamp(i,0,state.steps.length-1);render(o);}function move(d){stop();go(state.stepIndex+d);}function sched(){state.timer=setTimeout(()=>{if(state.stepIndex>=state.steps.length-1){stop();return;}go(state.stepIndex+1);if(state.stepIndex>=state.steps.length-1)stop();else sched();},PROBLEM.autoplayMs/state.speed);}function start(){if(!state.steps.length)return;stop();if(state.stepIndex>=state.steps.length-1)go(0);Core.updatePlaybackControls(els.playBtn,true);sched();}function reset(){stop();go(0);}
  function sampleButtons(){els.sampleButtons.replaceChildren();PROBLEM.samples.forEach(s=>{const b=document.createElement("button");b.type="button";b.className="btn";b.textContent=s.label;b.dataset.sample=s.id;b.classList.toggle("selected",state.selectedSample===s.id);els.sampleButtons.append(b);});}
  function apply(text,id=null){stop();try{state.steps=buildSteps(parseInput(text));state.stepIndex=0;state.selectedSample=id;els.inputError.textContent="";els.timeline.max=els.mobileTimeline.max=Math.max(0,state.steps.length-1);sampleButtons();render();}catch(e){state.selectedSample=null;els.inputError.textContent=e.message;sampleButtons();}}
  const markup=Core.createCodeMarkup(els.sourceCode,PROBLEM.sourceSteps,{wrap:false,editor:true});els.codeView.innerHTML=els.mobileCodeView.innerHTML=markup;desktopLines=Core.createLineMap(els.codeView);mobileLines=Core.createLineMap(els.mobileCodeView);stepLines=Core.createStepLineMap(els.codeView);
  els.prevBtn.onclick=()=>move(-1);els.nextBtn.onclick=()=>move(1);els.mobilePrevBtn.onclick=()=>move(-1);els.mobileNextBtn.onclick=()=>move(1);els.mobilePlayBtn.onclick=()=>els.playBtn.click();els.playBtn.onclick=()=>state.timer===null?start():stop();els.resetBtn.onclick=reset;els.replayBtn.onclick=()=>{reset();start();};els.skipBtn.onclick=()=>{stop();go(state.steps.length-1);};els.speedRange.oninput=()=>{state.speed=Number(els.speedRange.value);els.speedLabel.textContent=`${Core.formatDecimal(state.speed)}×`;if(state.timer!==null){clearTimeout(state.timer);sched();}};[els.timeline,els.mobileTimeline].forEach(x=>x.oninput=e=>{stop();go(Number(e.target.value));});els.applyBtn.onclick=()=>apply(els.inputArea.value);els.inputArea.oninput=()=>{state.selectedSample=null;sampleButtons();};els.sampleButtons.onclick=e=>{const b=e.target.closest("button[data-sample]");if(!b)return;const s=PROBLEM.samples.find(v=>v.id===b.dataset.sample);if(!s)return;els.inputArea.value=s.value;apply(s.value,s.id);};const d=PROBLEM.samples.find(s=>s.id===PROBLEM.defaultSampleId);sampleButtons();els.inputArea.value=d.value;apply(d.value,d.id);
})();