(() => {
  const Core = window.AlgoriZoomCore;
  const PROBLEM=Object.freeze({number:"5207",title:"이진 탐색",autoplayMs:560,defaultSampleId:"all",samples:[
    {id:"one",label:"샘플 1",value:"1\n3 3\n1 2 3\n2 3 4"},
    {id:"two",label:"샘플 2",value:"1\n3 5\n1 3 5\n2 4 6 8 10"},
    {id:"three",label:"샘플 3",value:"1\n5 5\n1 3 5 7 9\n1 2 3 4 5"},
    {id:"all",label:"전체 샘플",value:"3\n3 3\n1 2 3\n2 3 4\n3 5\n1 3 5\n2 4 6 8 10\n5 5\n1 3 5 7 9\n1 2 3 4 5"}
  ],sourceSteps:[
    {text:"A = list(map(int, input().split()))",types:"inputA"},{text:"B = list(map(int, input().split()))",types:"inputB"},{text:"A.sort()",types:"sortA"},{text:"ans = 0",types:"ansInit"},{text:"for target in B:",types:"targetLoop"},{text:"l = 0",types:"leftInit"},{text:"r = N - 1",types:"rightInit"},{text:"direction = ''",types:"dirInit"},{text:"while l <= r:",types:"whileCheck"},{text:"m = (l + r) // 2",types:"midCalc"},{text:"if A[m] == target:",types:"foundCheck"},{text:"ans += 1",types:"ansInc"},{text:"break",types:"foundBreak",occurrence:1},{text:"if A[m] > target:",types:"goLeft"},{text:"if direction == 'left':",types:"repeatLeft"},{text:"break",types:"leftBreak",occurrence:2},{text:"r = m - 1",types:"moveRightBound"},{text:"direction = 'left'",types:"setLeft"},{text:"elif A[m] < target:",types:"goRight"},{text:"if direction == 'right':",types:"repeatRight"},{text:"break",types:"rightBreak",occurrence:3},{text:"l = m + 1",types:"moveLeftBound"},{text:"direction = 'right'",types:"setRight"},{text:"print('#{} {}'.format(tc, ans))",types:"output"}
  ]});
  const els=Core.getByIds(["sourceCode","codeView","mobileCodeView","codeViewport","mobileCodeViewport","resetBtn","prevBtn","nextBtn","playBtn","replayBtn","skipBtn","speedRange","speedLabel","timeline","mobileTimeline","stepLabel","mobileTimelineStatus","mobilePlayBtn","mobilePrevBtn","mobileNextBtn","codeLineLabel","mobileCodeStatus","board","mobileBoard","boardLabel","phaseLabel","mobilePhase","targetValue","leftValue","midValue","rightValue","directionValue","ansValue","explainText","mobileCoord","mobileExplanation","mobileStateMeta","mobileTarget","mobileLeft","mobileMid","mobileRight","detailView","mobileDetailView","detailMeta","outputView","mobileOutputView","inputArea","applyBtn","sampleButtons","inputError"]);
  const state={steps:[],stepIndex:0,timer:null,speed:1,selectedSample:PROBLEM.defaultSampleId};let desktopLines,mobileLines,stepLines;

  function parseInput(text){const t=text.trim().split(/\s+/).filter(Boolean).map(Number);if(!t.length||t.some(v=>!Number.isFinite(v)))throw new Error("숫자로 된 입력을 확인해주세요.");let p=0,T=t[p++],cases=[];if(!Number.isInteger(T)||T<1||T>10)throw new Error("시각화에서는 T를 1~10으로 입력해주세요.");for(let tc=0;tc<T;tc++){let N=t[p++],M=t[p++];if(!Number.isInteger(N)||!Number.isInteger(M)||N<1||M<1||N>80||M>80)throw new Error(`#${tc+1}의 N, M은 시각화를 위해 1~80으로 입력해주세요.`);if(p+N+M>t.length)throw new Error(`#${tc+1}의 A 또는 B 원소가 부족합니다.`);let A=t.slice(p,p+N);p+=N;let B=t.slice(p,p+M);p+=M;if([...A,...B].some(v=>!Number.isInteger(v)||v<=0||v>1000000))throw new Error("A와 B의 값은 1~1,000,000의 양의 정수여야 합니다.");if(new Set(A).size!==A.length)throw new Error("A의 원소는 서로 달라야 합니다.");cases.push({N,M,A,B});}if(p!==t.length)throw new Error("입력 끝에 사용되지 않은 값이 있습니다.");return cases;}

  function buildSteps(cases){const steps=[];let output="";cases.forEach((item,ci)=>{let A=[...item.A],B=[...item.B],ans=0,results=[];const push=(phase,message,extra={})=>steps.push({tc:ci+1,N:item.N,M:item.M,A:[...A],B:[...B],ans,target:null,targetIndex:null,l:null,m:null,r:null,direction:"",path:[],results:results.map(v=>({...v,path:[...v.path]})),phase,message,output,...extra,path:[...(extra.path||[])]});push("inputA",`#${ci+1} A 입력 순서: ${A.join(", ")}`);push("inputB",`B에서 찾을 값: ${B.join(", ")}`);A.sort((a,b)=>a-b);push("sortA",`A를 오름차순으로 정렬합니다: ${A.join(", ")}`);push("ansInit","조건을 만족하며 찾은 target 수 ans를 0으로 초기화합니다.");
    B.forEach((target,targetIndex)=>{let l=0,r=item.N-1,m=null,direction="",path=[],finished=false,success=false,reason="";const snap=(phase,message,extra={})=>push(phase,message,{target,targetIndex,l,m,r,direction,path,...extra});snap("targetLoop",`B[${targetIndex}] = ${target}을 A에서 이진 탐색합니다.`);snap("leftInit","왼쪽 경계 l을 0으로 둡니다.");snap("rightInit",`오른쪽 경계 r을 ${r}로 둡니다.`);snap("dirInit","아직 선택한 방향이 없으므로 direction = ''로 시작합니다.");while(l<=r&&!finished){snap("whileCheck",`l ≤ r → ${l} ≤ ${r}. 현재 탐색 구간을 계속 확인합니다.`);m=(l+r)>>1;snap("midCalc",`m = (${l} + ${r}) // 2 = ${m}, A[m] = ${A[m]}입니다.`);const found=A[m]===target;snap("foundCheck",`A[${m}] == ${target} → ${found?"참":"거짓"}`);if(found){ans+=1;success=true;reason="찾음";snap("ansInc",`target ${target}을 찾았고 방향 조건도 어기지 않았으므로 ans를 ${ans}로 증가시킵니다.`,{found:true});snap("foundBreak","이 target의 탐색을 종료합니다.",{found:true});finished=true;break;}if(A[m]>target){snap("goLeft",`${A[m]} > ${target}이므로 왼쪽 구간을 선택해야 합니다.`);const repeated=direction==="left";snap("repeatLeft",`direction == 'left' → ${repeated?"참":"거짓"}`);if(repeated){reason="왼쪽 연속 선택";snap("leftBreak","직전에도 왼쪽을 선택했으므로 조건 위반으로 탐색을 종료합니다.",{invalid:true});finished=true;break;}r=m-1;snap("moveRightBound",`r을 m - 1 = ${r}로 줄입니다.`);direction="left";path.push("left");snap("setLeft","direction을 'left'로 기록합니다.");}else{snap("goRight",`${A[m]} < ${target}이므로 오른쪽 구간을 선택해야 합니다.`);const repeated=direction==="right";snap("repeatRight",`direction == 'right' → ${repeated?"참":"거짓"}`);if(repeated){reason="오른쪽 연속 선택";snap("rightBreak","직전에도 오른쪽을 선택했으므로 조건 위반으로 탐색을 종료합니다.",{invalid:true});finished=true;break;}l=m+1;snap("moveLeftBound",`l을 m + 1 = ${l}로 늘립니다.`);direction="right";path.push("right");snap("setRight","direction을 'right'로 기록합니다.");}}
      if(!finished){reason="A에 없음";snap("whileCheck",`l=${l} > r=${r}이 되어 ${target}은 A에서 찾지 못했습니다.`,{notFound:true});}
      results.push({target,success,reason,path:[...path]});
    });
    output+=`#${ci+1} ${ans}\n`;push("output",`#${ci+1}에서 조건을 만족한 target은 ${ans}개입니다.`);});return steps;}

  const names={inputA:"A 입력",inputB:"B 입력",sortA:"A 정렬",ansInit:"ans 초기화",targetLoop:"target 선택",leftInit:"l 초기화",rightInit:"r 초기화",dirInit:"direction 초기화",whileCheck:"탐색 구간 확인",midCalc:"중앙값 계산",foundCheck:"target 비교",ansInc:"정답 증가",foundBreak:"target 탐색 종료",goLeft:"왼쪽 선택",repeatLeft:"왼쪽 연속 확인",leftBreak:"조건 위반 종료",moveRightBound:"r 이동",setLeft:"direction=left",goRight:"오른쪽 선택",repeatRight:"오른쪽 연속 확인",rightBreak:"조건 위반 종료",moveLeftBound:"l 이동",setRight:"direction=right",output:"출력"};
  function board(container,s){const aCells=s.A.map((v,i)=>{const cls=["num-cell"];if(s.l!==null&&s.r!==null&&(i<s.l||i>s.r))cls.push("outside");else if(s.l!==null&&s.r!==null)cls.push("range");if(i===s.m)cls.push("mid");if(i===s.m&&v===s.target)cls.push("found");return `<span class="${cls.join(" ")}">${v}<small>${i}</small></span>`}).join("");const resultMap=new Map(s.results.map(v=>[v.targetIndex??-1,v]));const bCells=s.B.map((v,i)=>{const past=s.results[i];const cls=["target-chip"];if(i===s.targetIndex)cls.push("current");if(past)cls.push(past.success?"success":"fail");return `<span class="${cls.join(" ")}">${v}</span>`}).join("");const dirs=s.path.length?s.path.map(d=>`<span class="direction-badge ${d}">${d==="left"?"← left":"right →"}</span>`).join(""):'<span class="direction-badge">아직 방향 선택 없음</span>';container.innerHTML=`<div class="search-wrap"><div><p class="section-title"><span>A ${s.phase==="inputA"?"· 입력 순서":"· 탐색 배열"}</span><span>${s.l===null?"전체":`구간 [${s.l}, ${s.r}]`}</span></p><div class="number-row">${aCells}</div></div><div><p class="section-title"><span>B · target 순서</span><span>${s.targetIndex===null?"대기":`${s.targetIndex+1}/${s.M}`}</span></p><div class="number-row">${bCells}</div></div><div class="direction-line">${dirs}</div></div>`;}
  function detail(container,s){if(!s.results.length){container.innerHTML='<span class="result-chip">아직 완료된 target이 없습니다.</span>';return;}container.innerHTML=s.results.map(v=>`<span class="result-chip ${v.success?"success":"fail"}"><strong>${v.target}</strong> · ${v.success?"성공":"제외"} · ${v.reason}${v.path.length?` · ${v.path.map(d=>d==="left"?"L":"R").join("→")}`:""}</span>`).join("");}
  function highlight(lines,n){lines.forEach((line,k)=>line.classList.toggle("active",k===n));}
  function renderD(s){let ln=stepLines.get(s.phase);highlight(desktopLines,ln);board(els.board,s);detail(els.detailView,s);els.codeLineLabel.textContent=ln?`LINE ${ln}`:names[s.phase];els.boardLabel.textContent=`#${s.tc} · N=${s.N}, M=${s.M}`;els.phaseLabel.textContent=names[s.phase];els.targetValue.textContent=s.target??"—";els.leftValue.textContent=s.l??"—";els.midValue.textContent=s.m??"—";els.rightValue.textContent=s.r??"—";els.directionValue.textContent=s.direction||"—";els.ansValue.textContent=s.ans;els.explainText.textContent=s.message;els.detailMeta.textContent=`완료 ${s.results.length}/${s.M}`;els.outputView.textContent=s.output||"아직 출력이 없습니다.";}
  function renderM(s){let ln=stepLines.get(s.phase);highlight(mobileLines,ln);board(els.mobileBoard,s);detail(els.mobileDetailView,s);els.mobileCoord.textContent=`#${s.tc} · ans = ${s.ans}`;els.mobileCodeStatus.textContent=ln?`LINE ${ln}`:names[s.phase];els.mobilePhase.textContent=names[s.phase];els.mobileExplanation.textContent=s.message;els.mobileStateMeta.textContent=s.direction?`direction = ${s.direction}`:`완료 ${s.results.length}/${s.M}`;els.mobileTarget.textContent=s.target??"—";els.mobileLeft.textContent=s.l??"—";els.mobileMid.textContent=s.m??"—";els.mobileRight.textContent=s.r??"—";els.mobileOutputView.textContent=s.output||"아직 출력이 없습니다.";}
  function sync(){let e=!state.steps.length;els.prevBtn.disabled=els.mobilePrevBtn.disabled=e||state.stepIndex===0;els.nextBtn.disabled=els.mobileNextBtn.disabled=e||state.stepIndex===state.steps.length-1;[els.playBtn,els.replayBtn,els.resetBtn,els.skipBtn,els.timeline,els.mobileTimeline,els.mobilePlayBtn].forEach(x=>x.disabled=e)}function render({follow=true}={}){let s=state.steps[state.stepIndex];if(!s)return;renderD(s);renderM(s);els.timeline.value=els.mobileTimeline.value=state.stepIndex;els.stepLabel.textContent=els.mobileTimelineStatus.textContent=`${state.stepIndex+1} / ${state.steps.length}`;sync();if(follow){let ln=stepLines.get(s.phase);if(ln){Core.centerInsideViewport(els.codeViewport,desktopLines.get(ln),{horizontal:false});Core.centerInsideViewport(els.mobileCodeViewport,mobileLines.get(ln),{horizontal:false});}}}
  function stop(){if(state.timer!==null)clearTimeout(state.timer);state.timer=null;Core.updatePlaybackControls(els.playBtn,false)}function go(i,o={}){if(!state.steps.length)return;state.stepIndex=Core.clamp(i,0,state.steps.length-1);render(o)}function move(d){stop();go(state.stepIndex+d)}function sched(){state.timer=setTimeout(()=>{if(state.stepIndex>=state.steps.length-1){stop();return}go(state.stepIndex+1);if(state.stepIndex>=state.steps.length-1)stop();else sched()},PROBLEM.autoplayMs/state.speed)}function start(){if(!state.steps.length)return;stop();if(state.stepIndex>=state.steps.length-1)go(0);Core.updatePlaybackControls(els.playBtn,true);sched()}function reset(){stop();go(0)}function sampleButtons(){els.sampleButtons.replaceChildren();PROBLEM.samples.forEach(s=>{let b=document.createElement("button");b.type="button";b.className="btn";b.textContent=s.label;b.dataset.sample=s.id;b.classList.toggle("selected",state.selectedSample===s.id);els.sampleButtons.append(b)})}function apply(text,id=null){stop();try{state.steps=buildSteps(parseInput(text));state.stepIndex=0;state.selectedSample=id;els.inputError.textContent="";els.timeline.max=els.mobileTimeline.max=Math.max(0,state.steps.length-1);sampleButtons();render()}catch(e){state.selectedSample=null;els.inputError.textContent=e.message;sampleButtons()}}
  const markup=Core.createCodeMarkup(els.sourceCode,PROBLEM.sourceSteps,{wrap:false,editor:true});els.codeView.innerHTML=els.mobileCodeView.innerHTML=markup;desktopLines=Core.createLineMap(els.codeView);mobileLines=Core.createLineMap(els.mobileCodeView);stepLines=Core.createStepLineMap(els.codeView);
  els.prevBtn.onclick=()=>move(-1);els.nextBtn.onclick=()=>move(1);els.mobilePrevBtn.onclick=()=>move(-1);els.mobileNextBtn.onclick=()=>move(1);els.mobilePlayBtn.onclick=()=>els.playBtn.click();els.playBtn.onclick=()=>state.timer===null?start():stop();els.resetBtn.onclick=reset;els.replayBtn.onclick=()=>{reset();start()};els.skipBtn.onclick=()=>{stop();go(state.steps.length-1)};els.speedRange.oninput=()=>{state.speed=Number(els.speedRange.value);els.speedLabel.textContent=`${Core.formatDecimal(state.speed)}×`;if(state.timer!==null){clearTimeout(state.timer);sched()}};[els.timeline,els.mobileTimeline].forEach(x=>x.oninput=e=>{stop();go(Number(e.target.value))});els.applyBtn.onclick=()=>apply(els.inputArea.value);els.inputArea.oninput=()=>{state.selectedSample=null;sampleButtons()};els.sampleButtons.onclick=e=>{let b=e.target.closest("button[data-sample]");if(!b)return;let s=PROBLEM.samples.find(v=>v.id===b.dataset.sample);if(!s)return;els.inputArea.value=s.value;apply(s.value,s.id)};let d=PROBLEM.samples.find(s=>s.id===PROBLEM.defaultSampleId);sampleButtons();els.inputArea.value=d.value;apply(d.value,d.id);
})();
